package forge

import (
	"bytes"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"strings"

	"gopkg.in/yaml.v3"
)

// labelTaxonomy is the document shape of .config/labels.yaml.
type labelTaxonomy struct {
	Version int     `yaml:"version"`
	Labels  []Label `yaml:"labels"`
}

// ParseLabelTaxonomy decodes a label taxonomy such as .config/labels.yaml into the labels
// ReconcileLabels writes. The document must be exactly one YAML document with version 1
// and 1 to MaxLabelsLimit labels; unknown keys are rejected, names must be nonempty,
// trimmed and unique, and colors must be six hexadecimal digits. A taxonomy that passes
// is therefore one GitHub accepts label by label, and one sync can write in one batch.
func ParseLabelTaxonomy(data []byte) ([]Label, error) {
	var taxonomy labelTaxonomy
	decoder := yaml.NewDecoder(bytes.NewReader(data))
	decoder.KnownFields(true)
	if err := decoder.Decode(&taxonomy); err != nil {
		return nil, fmt.Errorf("parse label taxonomy: %w", err)
	}
	var extra any
	if err := decoder.Decode(&extra); !errors.Is(err, io.EOF) {
		return nil, errors.New("label taxonomy requires exactly one document")
	}
	if taxonomy.Version != 1 || len(taxonomy.Labels) == 0 || len(taxonomy.Labels) > MaxLabelsLimit {
		return nil, fmt.Errorf("label taxonomy requires version 1 and 1-%d labels", MaxLabelsLimit)
	}
	if err := validateLabelEntries(taxonomy.Labels); err != nil {
		return nil, err
	}
	return taxonomy.Labels, nil
}

func validateLabelEntries(labels []Label) error {
	seen := make(map[string]bool, len(labels))
	for i := 0; i < len(labels) && i < MaxLabelsLimit; i++ {
		label := labels[i]
		name := strings.TrimSpace(label.Name)
		if name == "" || name != label.Name || seen[name] {
			return errors.New("label names must be nonempty, trimmed and unique")
		}
		if color, err := hex.DecodeString(label.Color); err != nil || len(color) != 3 {
			return errors.New("label colors must contain exactly six hexadecimal digits")
		}
		seen[name] = true
	}
	return nil
}

// defaultLabelTaxonomy is the canonical repository label taxonomy, in the .config/labels.yaml
// format. praetor's own .config/labels.yaml carries it byte for byte (labels_test.go).
//
// It used to exist twice: sync wrote eight labels and adoption wrote a three-label copy, so
// `adopt --force` truncated a repository's taxonomy to three.
//
// bug, enhancement, triage, rfc, api-review and dependencies are the labels the issue forms
// and the Renovate configuration apply; they were missing, so a label reconciliation could
// never create them (BUG-548). bug, enhancement and dependencies keep the colors and
// descriptions GitHub and Dependabot give them by default, so reconciling a repository that
// already has them changes nothing.
const defaultLabelTaxonomy = `# Canonical Repository Label Taxonomy
version: 1
labels:
  - name: "hiss-violation"
    color: "d73a4a"
    description: "Code introduces a regression against HISS invariants"

  - name: "hiss-waiver"
    color: "fbca04"
    description: "Requires cryptographically signed waiver approval"

  - name: "standards-sync"
    color: "0075ca"
    description: "Automated configuration sync generated by Praetor"

  - name: "flavor:bleeding"
    color: "e99695"
    description: "Dependencies or assets targeting bleeding-edge branch"

  - name: "flavor:latest"
    color: "0e8a16"
    description: "Dependencies or assets targeting latest stable release"

  - name: "flavor:lts"
    color: "5319e7"
    description: "Dependencies or assets targeting long-term support release"

  - name: "security:high"
    color: "b60205"
    description: "High-security facet: SLSA-3, Cosign, zero-CVE invariant"

  - name: "breaking-change"
    color: "b60205"
    description: "Breaking API change requiring mandatory Migration: footer"

  - name: "bug"
    color: "d73a4a"
    description: "Something isn't working"

  - name: "enhancement"
    color: "a2eeef"
    description: "New feature or request"

  - name: "triage"
    color: "ededed"
    description: "Awaiting maintainer triage"

  - name: "rfc"
    color: "c5def5"
    description: "Request for comments on a proposed change"

  - name: "api-review"
    color: "1d76db"
    description: "Changes a public API contract and needs API review"

  - name: "dependencies"
    color: "0366d6"
    description: "Pull requests that update a dependency file"
`

// DefaultLabelTaxonomy returns the canonical .config/labels.yaml that adoption and sync write
// into a repository that has none. It is a fresh copy on every call.
func DefaultLabelTaxonomy() []byte {
	return []byte(defaultLabelTaxonomy)
}
