package typegen

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/cordanaLLM/praetor/internal/clientschema"
)

// Target is one generated file: its repository path and the vendored schemas it is built from.
type Target struct {
	// Path is relative to the repository root.
	Path string
	// Package is the Go package of the file.
	Package string
	// Source is the manifest source the file is built from.
	Source string
	build  func(source clientschema.Source, pkg, header string) ([]byte, error)
}

// Targets lists every generated file, in path order.
func Targets() []Target {
	return []Target{
		{Path: "internal/codexhook/events_gen.go", Package: "codexhook", Source: "codex-hooks", build: buildCodexHooks},
		{Path: "internal/mcpwire/messages_gen.go", Package: "mcpwire", Source: "mcp-protocol", build: buildMCP},
	}
}

// mcpRoots are the MCP definitions Praetor's server receives and sends: the JSON-RPC envelopes,
// the initialize exchange, tool listing and tool calls.
var mcpRoots = []string{
	"CallToolRequestParams", "CallToolResult", "Error", "Implementation", "InitializeRequestParams",
	"InitializeResult", "JSONRPCErrorResponse", "JSONRPCNotification", "JSONRPCRequest",
	"JSONRPCResultResponse", "ListToolsResult", "ServerCapabilities", "TextContent", "Tool",
	"ToolAnnotations",
}

func buildMCP(source clientschema.Source, pkg, header string) ([]byte, error) {
	raw, err := clientschema.Read(source.Files[0])
	if err != nil {
		return nil, err
	}
	roots := make([]Root, 0, len(mcpRoots))
	for _, name := range mcpRoots {
		roots = append(roots, Root{Def: name, Name: name})
	}
	return Generate(pkg, header, raw, roots)
}

func buildCodexHooks(source clientschema.Source, pkg, header string) ([]byte, error) {
	sources := make([]Source, 0, len(source.Files))
	for _, file := range source.Files {
		raw, err := clientschema.Read(file)
		if err != nil {
			return nil, err
		}
		name, err := hookTypeName(file.Path)
		if err != nil {
			return nil, err
		}
		sources = append(sources, Source{Name: file.Path, Root: name, Schema: raw})
	}
	return GenerateMany(pkg, header, sources)
}

// hookTypeName turns "codex/hooks/pre-tool-use.command.input.schema.json" into
// "PreToolUseCommandInput".
func hookTypeName(path string) (string, error) {
	base := filepath.Base(path)
	stem, ok := strings.CutSuffix(base, ".schema.json")
	if !ok {
		return "", fmt.Errorf("hook schema %s does not end in .schema.json", path)
	}
	return goName(stem), nil
}

func header(source clientschema.Source) string {
	digests := sha256.New()
	for _, file := range source.Files {
		digests.Write([]byte(file.Path + " " + file.SHA256 + "\n"))
	}
	return fmt.Sprintf(`// SPDX-FileCopyrightText: 2026 Lusoris <lusoris@proton.me>
//
// SPDX-License-Identifier: EUPL-1.2

// Code generated by internal/clientschema/typegen from the vendored schemas of %s; DO NOT EDIT.
//
// Source: %s at %s (%s), %d files, digest %s.
// Regenerate: go generate ./internal/clientschema
`, source.ID, source.Repo, source.Pin, source.License, len(source.Files), hex.EncodeToString(digests.Sum(nil))[:16])
}

// Render builds the content of every target from the vendored schemas.
func Render() (map[string][]byte, error) {
	manifest, err := clientschema.LoadManifest()
	if err != nil {
		return nil, err
	}
	rendered := map[string][]byte{}
	for _, target := range Targets() {
		source, ok := manifest.Source(target.Source)
		if !ok {
			return nil, fmt.Errorf("target %s: no source %q in the manifest", target.Path, target.Source)
		}
		content, err := target.build(source, target.Package, header(source))
		if err != nil {
			return nil, fmt.Errorf("target %s: %w", target.Path, err)
		}
		rendered[target.Path] = content
	}
	return rendered, nil
}

// maxGeneratedBytes bounds one committed generated file that Check reads.
const maxGeneratedBytes = 4 << 20

// ErrStale marks a generated file that differs from what the vendored schemas generate.
var ErrStale = errors.New("generated file is stale")

// Check compares every target under root with its rendering and returns one error naming each
// file that is missing or differs.
func Check(root string) error {
	rendered, err := Render()
	if err != nil {
		return err
	}
	var stale []string
	for _, target := range Targets() {
		current, err := readBounded(filepath.Join(root, filepath.FromSlash(target.Path)))
		if err != nil || !bytes.Equal(current, rendered[target.Path]) {
			stale = append(stale, target.Path)
		}
	}
	if len(stale) > 0 {
		return fmt.Errorf("%w: %s (run go generate ./internal/clientschema)", ErrStale, strings.Join(stale, ", "))
	}
	return nil
}

// Write regenerates every target under root.
func Write(root string) error {
	rendered, err := Render()
	if err != nil {
		return err
	}
	for _, target := range Targets() {
		path := filepath.Join(root, filepath.FromSlash(target.Path))
		if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
			return fmt.Errorf("create %s: %w", filepath.Dir(path), err)
		}
		if err := os.WriteFile(path, rendered[target.Path], 0o600); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
	}
	return nil
}

func readBounded(path string) (data []byte, err error) {
	// #nosec G304 -- path joins the repository root the caller names with a fixed Targets path.
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer func() { err = errors.Join(err, file.Close()) }()
	data, err = io.ReadAll(io.LimitReader(file, maxGeneratedBytes+1))
	if err != nil {
		return nil, err
	}
	if len(data) > maxGeneratedBytes {
		return nil, errors.New("generated file exceeds its bound")
	}
	return data, nil
}
