package typegen

import (
	"encoding/json"
	"errors"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/cordanaLLM/praetor/internal/clientschema"
)

const repoRoot = "../../.."

// updateEnv regenerates the committed files instead of checking them, as the generated artefact
// declaration in internal/generated/builtin.go runs it.
const updateEnv = "PRAETOR_UPDATE_CLIENT_SCHEMA_TYPES"

// TestGeneratedTypesAreFresh is the staleness gate: the committed generated files equal what the
// vendored schemas generate. With the update variable set it rewrites them.
func TestGeneratedTypesAreFresh(t *testing.T) {
	if os.Getenv(updateEnv) == "1" {
		if err := Write(repoRoot); err != nil {
			t.Fatal(err)
		}
	}
	if err := Check(repoRoot); err != nil {
		t.Fatal(err)
	}
}

// copyVendor copies the vendor directory of the checkout into root, so Check and Write of that
// root read the same pinned bytes.
func copyVendor(t *testing.T, root string) {
	t.Helper()
	src := clientschema.VendorDir(repoRoot)
	dst := clientschema.VendorDir(root)
	err := filepath.WalkDir(src, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		rel, err := filepath.Rel(src, path)
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return os.MkdirAll(filepath.Join(dst, rel), 0o750)
		}
		data, err := os.ReadFile(path) // #nosec G304 -- test walk of the vendor directory.
		if err != nil {
			return err
		}
		return os.WriteFile(filepath.Join(dst, rel), data, 0o600)
	})
	if err != nil {
		t.Fatal(err)
	}
}

// copyTargets writes the current rendering into a fresh root, vendor directory included, and
// returns it.
func copyTargets(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	copyVendor(t, root)
	if err := Write(root); err != nil {
		t.Fatal(err)
	}
	return root
}

// TestCheckFailsAStaleGeneration plants the stale generation of rule 13: a generated file that
// no longer matches the schemas must fail the check and name the file; the regenerated file
// passes again.
func TestCheckFailsAStaleGeneration(t *testing.T) {
	root := copyTargets(t)
	if err := Check(root); err != nil {
		t.Fatalf("fresh generation fails: %v", err)
	}
	target := Targets()[0].Path
	path := filepath.Join(root, filepath.FromSlash(target))
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	stale := strings.Replace(string(data), "SessionId", "SessionID", 1)
	if stale == string(data) {
		t.Fatal("the planted change did not alter the file")
	}
	if err := os.WriteFile(path, []byte(stale), 0o644); err != nil {
		t.Fatal(err)
	}
	err = Check(root)
	if !errors.Is(err, ErrStale) || !strings.Contains(err.Error(), target) {
		t.Fatalf("Check(stale) = %v, want ErrStale naming %s", err, target)
	}
	if err := Write(root); err != nil {
		t.Fatal(err)
	}
	if err := Check(root); err != nil {
		t.Fatalf("regenerated file still stale: %v", err)
	}
}

func TestCheckFailsAMissingFile(t *testing.T) {
	root := copyTargets(t)
	target := Targets()[1].Path
	if err := os.Remove(filepath.Join(root, filepath.FromSlash(target))); err != nil {
		t.Fatal(err)
	}
	if err := Check(root); !errors.Is(err, ErrStale) || !strings.Contains(err.Error(), target) {
		t.Fatalf("Check(missing) = %v", err)
	}
}

func TestGeneratedFilesParseAndDeclareTheirPins(t *testing.T) {
	rendered, err := Render(repoRoot)
	if err != nil {
		t.Fatal(err)
	}
	if len(rendered) != len(Targets()) {
		t.Fatalf("rendered %d files for %d targets", len(rendered), len(Targets()))
	}
	for path, content := range rendered {
		if _, err := parser.ParseFile(token.NewFileSet(), path, content, parser.AllErrors); err != nil {
			t.Errorf("%s does not parse: %v", path, err)
		}
		text := string(content)
		if !strings.Contains(text, "Code generated by") || !strings.Contains(text, "DO NOT EDIT") || !strings.Contains(text, "digest ") {
			t.Errorf("%s lacks the generated marker or the source digest", path)
		}
	}
}

const sample = `{
  "$defs": {
    "Kind": {"type": "string", "enum": ["a-b", "c"]},
    "Name": {"type": ["string", "null"]},
    "Item": {"type": "object", "required": ["id"], "properties": {"id": {"type": "integer"}, "tags": {"type": "array", "items": {"type": "string"}}}},
    "Box": {
      "description": "A box. It holds items.",
      "type": "object",
      "required": ["kind", "item"],
      "properties": {
        "kind": {"$ref": "#/$defs/Kind"},
        "item": {"$ref": "#/$defs/Item"},
        "name": {"$ref": "#/$defs/Name"},
        "grid": {"type": "array", "items": {"type": "array", "items": {"type": "number"}}},
        "flag": {"type": "boolean"},
        "wrapped": {"allOf": [{"$ref": "#/$defs/Item"}]},
        "free": {"type": "object"},
        "union": {"anyOf": [{"type": "string"}, {"type": "integer"}]},
        "maybe": {"anyOf": [{"type": "string"}, {"type": "null"}]},
        "fixed": {"const": "box", "type": "string"},
        "inline": {"type": "object", "properties": {"x": {"type": "string"}}}
      }
    }
  }
}`

func TestGeneratePositive(t *testing.T) {
	out, err := Generate("sample", "// header\n", []byte(sample), []Root{{Def: "Box", Name: "Box"}})
	if err != nil {
		t.Fatal(err)
	}
	text := string(out)
	for _, want := range []string{
		"package sample", "type Kind string", `KindAB Kind = "a-b"`, "type Name = *string",
		"Kind  Kind `json:\"kind\"`", "Item  Item `json:\"item\"`", "Grid [][]float64 `json:\"grid,omitempty\"`",
		"Flag *bool `json:\"flag,omitempty\"`", "Wrapped *Item", "Free *map[string]any", "Union json.RawMessage",
		"Maybe *string", "Fixed *string", "BoxInline", "// Box is generated from the vendored schema: A box.",
	} {
		if !strings.Contains(strings.Join(strings.Fields(text), " "), strings.Join(strings.Fields(want), " ")) {
			t.Errorf("generated source lacks %q:\n%s", want, text)
		}
	}
	if _, err := parser.ParseFile(token.NewFileSet(), "sample.go", out, 0); err != nil {
		t.Fatalf("generated source does not parse: %v\n%s", err, text)
	}
}

func TestGenerateRefusals(t *testing.T) {
	cases := map[string]struct {
		schema string
		roots  []Root
	}{
		"not an object":      {`[]`, []Root{{Name: "X"}}},
		"missing definition": {sample, []Root{{Def: "Nope", Name: "Nope"}}},
		"external reference": {`{"type":"object","properties":{"a":{"$ref":"https://example.invalid/x.json#/$defs/A"}}}`, []Root{{Name: "X"}}},
		"dangling reference": {`{"type":"object","properties":{"a":{"$ref":"#/$defs/Gone"}}}`, []Root{{Name: "X"}}},
		"name collision":     {`{"type":"object","properties":{"a_b":{"type":"string"},"aB":{"type":"string"}}}`, []Root{{Name: "X"}}},
	}
	for name, c := range cases {
		if _, err := Generate("p", "", []byte(c.schema), c.roots); err == nil {
			t.Errorf("%s: accepted", name)
		}
	}
}

func TestGenerateManyRefusesTwoDifferentDefinitionsOfOneName(t *testing.T) {
	a := Source{Name: "a", Root: "A", Schema: []byte(`{"type":"object","properties":{"x":{"$ref":"#/definitions/Shared"}},"definitions":{"Shared":{"type":"string"}}}`)}
	same := Source{Name: "b", Root: "B", Schema: []byte(`{"type":"object","properties":{"y":{"$ref":"#/definitions/Shared"}},"definitions":{"Shared":{"type":"string"}}}`)}
	other := Source{Name: "c", Root: "C", Schema: []byte(`{"type":"object","properties":{"z":{"$ref":"#/definitions/Shared"}},"definitions":{"Shared":{"type":"integer"}}}`)}
	if _, err := GenerateMany("p", "", []Source{a, same}); err != nil {
		t.Errorf("identical shared definition refused: %v", err)
	}
	if _, err := GenerateMany("p", "", []Source{a, other}); err == nil {
		t.Error("two different Shared definitions merged silently")
	}
}

func TestGoNameBoundaries(t *testing.T) {
	cases := map[string]string{"a-b": "AB", "_meta": "Meta", "9lives": "X9lives", "": "X", "hook_event_name": "HookEventName", "already": "Already"}
	for in, want := range cases {
		if got := goName(in); got != want {
			t.Errorf("goName(%q) = %q, want %q", in, got, want)
		}
	}
}

// An object with no named member never becomes an empty struct, which would drop every member;
// an object with named members keeps the rest in Extra unless its schema closes it. The empty
// and the single-member boundaries are both covered.
func TestGenerateKeepsOpenObjects(t *testing.T) {
	const schema = `{"$defs": {
	  "Root": {"type": "object", "properties": {
	    "emptyOpen": {"type": "object", "properties": {}, "additionalProperties": true},
	    "emptySchema": {"type": "object", "properties": {}, "additionalProperties": {}},
	    "namedOpen": {"type": "object", "properties": {"id": {"type": "string"}}, "additionalProperties": {}},
	    "typedValues": {"type": "object", "additionalProperties": {"type": "string"}},
	    "namedClosed": {"type": "object", "properties": {"id": {"type": "string"}}, "additionalProperties": false},
	    "namedUnstated": {"type": "object", "properties": {"id": {"type": "string"}}},
	    "noType": {"properties": {"id": {"type": "string"}}, "additionalProperties": true}
	  }, "additionalProperties": false},
	  "Bare": {"type": "object", "properties": {}, "additionalProperties": true}
	}}`
	out, err := Generate("p", "", []byte(schema), []Root{{Def: "Root", Name: "Root"}, {Def: "Bare", Name: "Bare"}})
	if err != nil {
		t.Fatal(err)
	}
	text := strings.Join(strings.Fields(string(out)), " ")
	for _, want := range []string{
		"EmptyOpen *map[string]any", "EmptySchema *map[string]any", "TypedValues *map[string]string", "type Bare = map[string]any",
		"NamedOpen *RootNamedOpen", "NamedUnstated *RootNamedUnstated", "NamedClosed *RootNamedClosed", "NoType *RootNoType",
		"func (v *RootNamedOpen) UnmarshalJSON", "func (v RootNamedUnstated) MarshalJSON", "func (v *RootNoType) UnmarshalJSON",
	} {
		if !strings.Contains(text, want) {
			t.Errorf("generated source lacks %q:\n%s", want, out)
		}
	}
	for _, unwanted := range []string{"type RootEmptyOpen", "type Bare struct", "RootNamedClosed) UnmarshalJSON", "func (v *Root) UnmarshalJSON"} {
		if strings.Contains(text, unwanted) {
			t.Errorf("generated source contains %q:\n%s", unwanted, out)
		}
	}
	if got := strings.Count(text, "Extra map[string]json.RawMessage"); got != 3 {
		t.Errorf("%d open structs carry Extra, want RootNamedOpen, RootNamedUnstated and RootNoType", got)
	}
	if _, err := parser.ParseFile(token.NewFileSet(), "open.go", out, 0); err != nil {
		t.Fatalf("generated source does not parse: %v\n%s", err, out)
	}
	clash := `{"type":"object","properties":{"extra":{"type":"string"}}}`
	if _, err := Generate("p", "", []byte(clash), []Root{{Name: "X"}}); err == nil {
		t.Error("a property named extra collided with the Extra member silently")
	}
}

func TestGenerateDepthBound(t *testing.T) {
	curr := map[string]any{"type": "string"}
	for i := 0; i < 65; i++ {
		curr = map[string]any{
			"type":                 "object",
			"additionalProperties": curr,
		}
	}
	root := map[string]any{
		"$defs": map[string]any{
			"Deep": curr,
		},
	}
	raw, err := json.Marshal(root)
	if err != nil {
		t.Fatal(err)
	}
	_, err = Generate("p", "", raw, []Root{{Def: "Deep", Name: "Deep"}})
	if err == nil {
		t.Fatal("expected depth bound error for 65 levels of nesting, got nil")
	}
	if !strings.Contains(err.Error(), "nesting too deep") {
		t.Fatalf("expected nesting too deep error, got: %v", err)
	}
}
