package flavor_test

// The scaffolded Node CI job must pass as written wherever flavor apply writes it. Adoption
// makes every job of a scaffolded workflow a required status check, and typescript-node
// detects any package.json: a Go repository carrying a package.json for its commit tooling used
// to receive `npm ci` + `npm test` as a check no pull request could pass, and a pnpm, Yarn or Bun
// project got no job at all (BUG-1011). The job runs on CI's checkout, not the working tree, so
// a lockfile Git never commits counts as no lockfile.

import (
	"encoding/json"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"testing"

	"github.com/cordanaLLM/praetor/internal/flavor"
	"github.com/cordanaLLM/praetor/internal/ghworkflow"
	"github.com/cordanaLLM/praetor/internal/nodemanifest"
	"github.com/cordanaLLM/praetor/templates"
	"gopkg.in/yaml.v3"
)

const nodeCIPath = ".github/workflows/ci.yml"

// npmLock is a package-lock.json npm ci accepts for a package with no dependencies.
const npmLock = `{"name": "widget", "lockfileVersion": 3, "requires": true, "packages": {"": {"name": "widget"}}}` + "\n"

// Lockfile bodies for the other managers. The model below reads only their names.
const (
	pnpmLock   = "lockfileVersion: '9.0'\n"
	yarnV1Lock = "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n"
	yarnV2Lock = "__metadata:\n  version: 8\n"
	bunLock    = "{\"lockfileVersion\": 1, \"workspaces\": {\"\": {\"name\": \"widget\"}}}\n"
)

// setupNodeLockfiles are the files setup-node's `cache: npm` looks for in the repository root;
// with none of them the action fails the job (actions/setup-node src/cache-utils.ts,
// findLockFile in src/cache-restore.ts).
var setupNodeLockfiles = []string{"package-lock.json", "npm-shrinkwrap.json", "yarn.lock"}

// lockedInstalls are the install commands the check models, each with the lockfiles it reads
// and, for Yarn, the major line whose flag it is: Yarn 2+ spells the locked install --immutable
// and Yarn 1 --frozen-lockfile. The table is this test's own, not nodemanifest's, so the two
// cannot share a mistake about which manager reads which lockfile.
var lockedInstalls = map[string]struct {
	lockfiles []string
	yarnBerry *bool
}{
	"npm ci":                         {lockfiles: []string{"package-lock.json"}},
	"pnpm install --frozen-lockfile": {lockfiles: []string{"pnpm-lock.yaml"}},
	"yarn install --frozen-lockfile": {lockfiles: []string{"yarn.lock"}, yarnBerry: new(false)},
	"yarn install --immutable":       {lockfiles: []string{"yarn.lock"}, yarnBerry: new(true)},
	"bun install --frozen-lockfile":  {lockfiles: []string{"bun.lock", "bun.lockb"}},
}

// nodeWorkflow is the part of a workflow the runnability check reads.
type nodeWorkflow struct {
	Jobs map[string]struct {
		Steps []struct {
			Uses string            `yaml:"uses"`
			With map[string]string `yaml:"with"`
			Run  string            `yaml:"run"`
		} `yaml:"steps"`
	} `yaml:"jobs"`
}

// nodeJob is what a Node CI job has installed so far, and the checkout it runs on.
type nodeJob struct {
	checkout map[string]bool
	scripts  map[string]string
	// declared is the manager packageManager names, "" for none; yarnBerry is whether the Yarn
	// Corepack runs there is 2 or later.
	declared  string
	yarnBerry bool
	tools     map[string]bool
}

// unrunnableNodeSteps returns every step of a Node workflow that cannot pass on CI's checkout of
// repo: an action whose inputs the checkout does not satisfy, a command naming a lockfile,
// script or tool that is not there, and any action or command the check does not model, so a
// later body cannot add one unchecked. The hosted gate's draft step is not read (draftSteps): it
// runs on a draft alone and fails it by design, so a ready pull request never runs it.
func unrunnableNodeSteps(t *testing.T, body, repo string) []string {
	t.Helper()
	var workflow nodeWorkflow
	if err := yaml.Unmarshal([]byte(body), &workflow); err != nil {
		t.Fatalf("parse workflow: %v\n%s", err, body)
	}
	spec, err := ghworkflow.Parse([]byte(body))
	if err != nil {
		t.Fatalf("parse workflow: %v\n%s", err, body)
	}
	var problems []string
	for id, steps := range workflow.Jobs {
		job := newNodeJob(t, repo)
		for i := draftSteps(spec.Jobs[id].Steps); i < len(steps.Steps) && i < maxWorkflowSteps; i++ {
			step := steps.Steps[i]
			if step.Uses != "" {
				problems = append(problems, job.action(step.Uses, step.With)...)
			}
			problems = append(problems, job.commands(step.Run)...)
		}
	}
	return problems
}

// draftSteps is how many leading steps of a job a ready pull request never runs: one when the
// first is the hosted gate's draft step (ghworkflow.DraftStepFault), none otherwise.
func draftSteps(steps []ghworkflow.Step) int {
	if len(steps) > 0 && ghworkflow.DraftStepFault(&steps[0]) == nil {
		return 1
	}
	return 0
}

func newNodeJob(t *testing.T, repo string) *nodeJob {
	t.Helper()
	manifest := readFixtureManifest(t, repo)
	declared, version, _ := strings.Cut(manifest.packageManager, "@")
	yarnrc, err := os.ReadFile(filepath.Join(repo, ".yarnrc.yml"))
	if err != nil && !os.IsNotExist(err) {
		t.Fatalf("read .yarnrc.yml: %v", err)
	}
	berry := strings.HasPrefix(string(yarnrc), "yarnPath:") || strings.Contains(string(yarnrc), "\nyarnPath:")
	if declared == "yarn" {
		major, _, _ := strings.Cut(version, ".")
		n, err := strconv.Atoi(major)
		berry = err == nil && n >= 2
	}
	return &nodeJob{checkout: checkoutFiles(t, repo), scripts: manifest.scripts, declared: declared, yarnBerry: berry, tools: map[string]bool{}}
}

// maxCheckoutFiles bounds the files read from one fixture's index (HISS-02).
const maxCheckoutFiles = 4096

// checkoutFiles returns the slash paths CI's checkout of repo would hold once its working tree
// is committed: what `git add -A` stages. Git leaves out an untracked file the repository's
// ignore rules exclude and keeps one already tracked, whatever the rules say. The model is
// Git's own staging, not the check-ignore query nodeCIRequirement makes, so the two cannot share
// a mistake about which files a checkout carries.
func checkoutFiles(t *testing.T, repo string) map[string]bool {
	t.Helper()
	runFixtureGit(t, repo, "add", "-A")
	names := strings.Split(string(runFixtureGit(t, repo, "ls-files", "-z")), "\x00")
	files := make(map[string]bool, len(names))
	for i := 0; i < len(names) && i < maxCheckoutFiles; i++ {
		if names[i] != "" {
			files[names[i]] = true
		}
	}
	return files
}

func (job *nodeJob) action(uses string, with map[string]string) []string {
	switch {
	case strings.HasPrefix(uses, "actions/checkout@"):
		return nil
	case strings.HasPrefix(uses, "actions/setup-node@"):
		job.tools["npm"] = true
		if with["cache"] == "npm" && !slices.ContainsFunc(setupNodeLockfiles, func(name string) bool { return job.checkout[name] }) {
			return []string{uses + ": cache: npm finds no lockfile"}
		}
		return nil
	case strings.HasPrefix(uses, "oven-sh/setup-bun@") && len(with) == 0:
		job.tools["bun"] = true
		return nil
	default:
		return []string{uses + ": action not modelled by this check"}
	}
}

// maxRunLines bounds the lines read from one run: body (HISS-02).
const maxRunLines = 64

func (job *nodeJob) commands(run string) []string {
	var problems []string
	lines := strings.Split(run, "\n")
	for i := 0; i < len(lines) && i < maxRunLines; i++ {
		fields := strings.Fields(lines[i])
		if len(fields) == 0 || strings.HasPrefix(fields[0], "#") {
			continue
		}
		if problem := job.command(fields); problem != "" {
			problems = append(problems, problem)
		}
	}
	return problems
}

// command checks one command line against what the job has installed. Corepack comes from npm,
// and `corepack enable <manager>` puts pnpm or Yarn on PATH; Corepack refuses a manager other
// than the one packageManager names.
func (job *nodeJob) command(fields []string) string {
	command := strings.Join(fields, " ")
	switch {
	case command == "npm install --global corepack@latest":
		return job.install("npm", "corepack", command)
	case command == "corepack enable pnpm" || command == "corepack enable yarn":
		return job.install("corepack", fields[2], command)
	case !slices.Contains([]string{"npm", "pnpm", "yarn", "bun"}, fields[0]):
		return command + ": command not modelled by this check"
	case !job.tools[fields[0]]:
		return command + ": no step installs " + fields[0]
	case job.declared != "" && job.declared != fields[0]:
		return command + ": package.json declares packageManager " + job.declared
	}
	return job.managerCommand(fields, command)
}

// install records tool as installed by a command that needs by.
func (job *nodeJob) install(by, tool, command string) string {
	if !job.tools[by] {
		return command + ": no step installs " + by
	}
	job.tools[tool] = true
	return ""
}

// managerCommand checks a package manager's own command: a locked install needs its lockfile in
// the checkout (and, for Yarn, the flag of the Yarn that runs), `npm test` and `<manager> run
// <name>` fail on a script that is missing or cannot pass, and --if-present, spelled where each
// manager reads it, makes an absent script a no-op. Yarn has no --if-present.
func (job *nodeJob) managerCommand(fields []string, command string) string {
	manager, args := fields[0], fields[1:]
	if install, ok := lockedInstalls[command]; ok {
		if !slices.ContainsFunc(install.lockfiles, func(name string) bool { return job.checkout[name] }) {
			return command + ": no " + strings.Join(install.lockfiles, " or ") + " in the checkout"
		}
		if install.yarnBerry != nil && *install.yarnBerry != job.yarnBerry {
			return command + ": not the locked-install flag of the Yarn that runs here"
		}
		return ""
	}
	switch {
	case manager == "npm" && len(args) == 3 && args[0] == "run" && args[2] == "--if-present":
		return ""
	case (manager == "pnpm" || manager == "bun") && len(args) == 3 && args[0] == "run" && args[1] == "--if-present":
		return ""
	case manager == "npm" && command == "npm test":
		return job.script("test", command)
	case len(args) == 2 && args[0] == "run" && !strings.HasPrefix(args[1], "-"):
		return job.script(args[1], command)
	}
	return command + ": command not modelled by this check"
}

func (job *nodeJob) script(name, command string) string {
	if !nodemanifest.ScriptRuns(job.scripts[name]) {
		return command + ": no " + name + " script that can pass"
	}
	return ""
}

// fixtureManifest is what the check reads from a fixture's package.json.
type fixtureManifest struct {
	packageManager string
	scripts        map[string]string
}

func readFixtureManifest(t *testing.T, repo string) fixtureManifest {
	t.Helper()
	var manifest fixtureManifest
	data, err := os.ReadFile(filepath.Join(repo, "package.json"))
	if os.IsNotExist(err) {
		return manifest
	}
	if err != nil {
		t.Fatalf("read package.json: %v", err)
	}
	// Exact keys, as npm reads them: a tagged struct field would also take "Scripts".
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		t.Fatalf("parse package.json: %v", err)
	}
	if raw, ok := fields["scripts"]; ok {
		if err := json.Unmarshal(raw, &manifest.scripts); err != nil {
			t.Fatalf("parse package.json scripts: %v", err)
		}
	}
	if raw, ok := fields["packageManager"]; ok {
		if err := json.Unmarshal(raw, &manifest.packageManager); err != nil {
			t.Fatalf("parse package.json packageManager: %v", err)
		}
	}
	return manifest
}

// nodeCICase is one repository shape and whether flavor apply may scaffold the Node CI job there.
type nodeCICase struct {
	name  string
	files map[string]string
	// track lists files Git tracks, force-added past any ignore rule; noGit leaves the fixture
	// outside a Git work tree.
	track []string
	noGit bool
	// flavor is what apply is asked for; "auto" exercises Resolve as adoption does.
	flavor string
	// runs are commands the scaffolded job must run; absent are commands it must not.
	runs   []string
	absent []string
	// unmet is a fragment of the reason the job was not scaffolded; "" means it was.
	unmet string
}

// repo builds the case's fixture.
func (tc nodeCICase) repo(t *testing.T) string {
	t.Helper()
	if tc.noGit {
		return repoWithFiles(t, tc.files)
	}
	repo := gitRepoWithFiles(t, tc.files)
	if len(tc.track) > 0 {
		runFixtureGit(t, repo, append([]string{"add", "-f", "--"}, tc.track...)...)
	}
	return repo
}

const commitTooling = `{"name": "widget-tooling", "private": true, "devDependencies": {"@commitlint/cli": "^20.0.0"}}` + "\n"

// goRepoWithCommitTooling is a Go service whose package.json only holds commit tooling, locked
// by pnpm.
func goRepoWithCommitTooling() map[string]string {
	return map[string]string{
		"go.mod": "module example.com/widget\n\ngo 1.27\n", "cmd/widget/main.go": "package main\n\nfunc main() {}\n",
		"internal/w/w.go": "package w\n", "package.json": commitTooling, "pnpm-lock.yaml": pnpmLock,
	}
}

const withTest = `{"name": "widget", "scripts": {"test": "node --test", "lint": "eslint ."}}` + "\n"

// npmCICases are the shapes the job first had to be withheld from, and the npm projects it runs in.
func npmCICases() []nodeCICase {
	ignoresLock := "node_modules/\npackage-lock.json\n"
	npmRuns := []string{"npm ci", "npm test"}
	return []nodeCICase{
		// Positive: an npm project with a committed lockfile and a test script.
		{name: "npm-project", files: map[string]string{"package.json": withTest, "package-lock.json": npmLock}, track: []string{"package.json", "package-lock.json"}, flavor: "typescript-node", runs: npmRuns},
		// Boundary: a lockfile not yet committed that nothing ignores goes into the next commit.
		{name: "npm-project-uncommitted-lockfile", files: map[string]string{"package.json": withTest, "package-lock.json": npmLock}, flavor: "typescript-node", runs: npmRuns},
		// Negative: a library that ignores package-lock.json while a local `npm install` has
		// written one. CI's checkout has no lockfile.
		{name: "ignored-lockfile", files: map[string]string{"package.json": withTest, "package-lock.json": npmLock, ".gitignore": ignoresLock}, flavor: "typescript-node", unmet: "untracked and git-ignored"},
		// Negative: a glob pattern excludes the lockfile just the same.
		{name: "ignored-by-glob", files: map[string]string{"package.json": withTest, "package-lock.json": npmLock, ".gitignore": "*-lock.json\n"}, flavor: "auto", unmet: "untracked and git-ignored"},
		// Boundary: a lockfile force-added past the ignore rule is tracked, so the checkout has it.
		{name: "ignored-but-tracked-lockfile", files: map[string]string{"package.json": withTest, "package-lock.json": npmLock, ".gitignore": ignoresLock}, track: []string{"package-lock.json"}, flavor: "typescript-node", runs: npmRuns},
		// Boundary: outside a Git work tree nothing says what CI checks out, so the job is withheld.
		{name: "not-a-git-work-tree", files: map[string]string{"package.json": withTest, "package-lock.json": npmLock}, noGit: true, flavor: "typescript-node", unmet: "cannot tell whether Git commits package-lock.json"},
		// Boundary: pinning npm itself through packageManager is still npm.
		{name: "npm-pinned", files: map[string]string{"package.json": `{"packageManager": "npm@11.15.0", "scripts": {"test": "vitest run"}}`, "package-lock.json": npmLock}, flavor: "typescript-node", runs: npmRuns},
		// Negative: the review's probe, a Go service whose package.json only holds commit tooling.
		// Resolution names go-service for it now (TestResolve_Positive_GoServiceWithCommitTooling);
		// applying typescript-node to it by name must still not write the job.
		{name: "go-repo-with-commit-tooling", files: goRepoWithCommitTooling(), flavor: "typescript-node", unmet: "no test script"},
		// Negative: the same tooling installed with npm keeps the placeholder test `npm init` writes.
		{name: "npm-init-placeholder", files: map[string]string{
			"package.json":      `{"name": "t", "scripts": {"test": "echo \"Error: no test specified\" && exit 1"}}`,
			"package-lock.json": npmLock,
		}, flavor: "typescript-node", unmet: "no test script"},
		{name: "no-test-script", files: map[string]string{"package.json": commitTooling, "package-lock.json": npmLock}, flavor: "typescript-node", unmet: "no test script"},
		// Boundary: npm-shrinkwrap.json satisfies setup-node but not npm 12's `npm ci`.
		{name: "shrinkwrap-only", files: map[string]string{"package.json": withTest, "npm-shrinkwrap.json": npmLock}, flavor: "typescript-node", unmet: "no package-lock.json"},
		// Boundary: an explicit apply to a repository with no package.json at all.
		{name: "no-package-json", files: map[string]string{}, flavor: "typescript-node", unmet: "package.json is unreadable"},
		// Boundary: npm reads "scripts" exactly; a "Scripts" key is not the test script.
		{name: "case-folded-scripts", files: map[string]string{"package.json": `{"Scripts": {"test": "node --test"}}`, "package-lock.json": npmLock}, flavor: "typescript-node", unmet: "no test script"},
	}
}

// managerCICases are pnpm, Yarn and Bun projects, which get a job in their own manager.
func managerCICases() []nodeCICase {
	return []nodeCICase{
		// Positive: the row's case, a pnpm project with no npm lockfile, detected as adoption does.
		{name: "pnpm-lock-only", files: map[string]string{"package.json": withTest, "pnpm-lock.yaml": pnpmLock}, flavor: "auto", runs: []string{"corepack enable pnpm", "pnpm install --frozen-lockfile", "pnpm run test"}, absent: []string{"npm ci"}},
		{name: "pnpm-declared", files: map[string]string{"package.json": `{"packageManager": "pnpm@10.0.0", "scripts": {"test": "vitest run"}}`, "pnpm-lock.yaml": pnpmLock}, flavor: "typescript-node", runs: []string{"pnpm install --frozen-lockfile"}},
		// Positive: Yarn 1 from its lockfile alone; only the scripts package.json defines run.
		{name: "yarn-classic-lock-only", files: map[string]string{"package.json": withTest, "yarn.lock": yarnV1Lock}, flavor: "typescript-node", runs: []string{"yarn install --frozen-lockfile", "yarn run lint", "yarn run test"}, absent: []string{"yarn run build"}},
		{name: "yarn-berry-declared", files: map[string]string{"package.json": `{"packageManager": "yarn@4.9.1+sha512.abc", "scripts": {"test": "jest", "build": "tsc"}}`, "yarn.lock": yarnV2Lock}, flavor: "typescript-node", runs: []string{"yarn install --immutable", "yarn run build", "yarn run test"}, absent: []string{"yarn run lint"}},
		// Boundary: undeclared, Yarn 1 hands over to the release .yarnrc.yml yarnPath names.
		{name: "yarn-berry-yarnpath", files: map[string]string{"package.json": withTest, "yarn.lock": yarnV2Lock, ".yarnrc.yml": "nodeLinker: node-modules\nyarnPath: .yarn/releases/yarn-4.9.1.cjs\n"}, flavor: "typescript-node", runs: []string{"yarn install --immutable"}},
		// Boundary: a .yarnrc.yml without yarnPath leaves Corepack's Yarn 1 in charge.
		{name: "yarnrc-without-yarnpath", files: map[string]string{"package.json": withTest, "yarn.lock": yarnV1Lock, ".yarnrc.yml": "nodeLinker: node-modules\n"}, flavor: "typescript-node", runs: []string{"yarn install --frozen-lockfile"}},
		{name: "bun-lock", files: map[string]string{"package.json": withTest, "bun.lock": bunLock}, flavor: "typescript-node", runs: []string{"bun install --frozen-lockfile", "bun run test"}, absent: []string{"bun test"}},
		// Boundary: Bun's binary lockfile from before 1.2 still counts.
		{name: "bun-lockb-declared", files: map[string]string{"package.json": `{"packageManager": "bun@1.3.0", "scripts": {"test": "bun test"}}`, "bun.lockb": "binary\n"}, flavor: "typescript-node", runs: []string{"bun install --frozen-lockfile"}},
		// Boundary: a declared manager decides even beside another manager's lockfile.
		{name: "pnpm-declared-beside-npm-lock", files: map[string]string{"package.json": `{"packageManager": "pnpm@10.0.0", "scripts": {"test": "vitest run"}}`, "pnpm-lock.yaml": pnpmLock, "package-lock.json": npmLock}, flavor: "typescript-node", runs: []string{"pnpm install --frozen-lockfile"}},
		// Boundary: an ignored npm lockfile does not compete with the committed pnpm one.
		{name: "ignored-npm-lock-beside-pnpm", files: map[string]string{"package.json": withTest, "pnpm-lock.yaml": pnpmLock, "package-lock.json": npmLock, ".gitignore": "package-lock.json\n"}, flavor: "typescript-node", runs: []string{"pnpm install --frozen-lockfile"}},
		// Negative: a declared manager other than npm is not satisfied by a stray npm lockfile.
		{name: "yarn-declared-npm-lock", files: map[string]string{"package.json": `{"packageManager": "yarn@4.9.1", "scripts": {"test": "jest"}}`, "package-lock.json": npmLock}, flavor: "typescript-node", unmet: "no yarn.lock"},
		{name: "bun-declared-no-lock", files: map[string]string{"package.json": `{"packageManager": "bun@1.3.0", "scripts": {"test": "bun test"}}`}, flavor: "typescript-node", unmet: "no bun.lock or bun.lockb"},
		// Negative: undeclared lockfiles of two managers leave the choice to the repository.
		{name: "two-managers-undeclared", files: map[string]string{"package.json": withTest, "pnpm-lock.yaml": pnpmLock, "package-lock.json": npmLock}, flavor: "typescript-node", unmet: "lockfiles of 2 package managers"},
		// Negative: a manager the job has no body for.
		{name: "unknown-manager", files: map[string]string{"package.json": `{"packageManager": "deno@2.0.0", "scripts": {"test": "deno test"}}`, "package-lock.json": npmLock}, flavor: "typescript-node", unmet: `packageManager "deno@2.0.0"`},
		{name: "unparseable-yarnrc", files: map[string]string{"package.json": withTest, "yarn.lock": yarnV1Lock, ".yarnrc.yml": "yarnPath: [\n"}, flavor: "typescript-node", unmet: ".yarnrc.yml does not parse"},
	}
}

func nodeCICases() []nodeCICase {
	return append(npmCICases(), managerCICases()...)
}

// The scaffolded job is written only where each of its steps can pass, and every step of the
// body it writes is checked against the fixture: every tool, lockfile and script it names exists.
func TestNodeCIJobIsScaffoldedOnlyWhereItRunsAsWritten(t *testing.T) {
	for _, tc := range nodeCICases() {
		t.Run(tc.name, func(t *testing.T) {
			repo := tc.repo(t)
			if tc.flavor == "auto" {
				if got, _ := resolve(repo); got != "typescript-node" {
					t.Fatalf("fixture detects %q, not typescript-node; the case no longer tests the job", got)
				}
			}
			report, err := flavor.ApplyFlavor(t.Context(), repo, tc.flavor, false)
			if err != nil || len(report.Errors) > 0 {
				t.Fatalf("apply: err %v, recorded %v", err, report.Errors)
			}
			data, readErr := os.ReadFile(filepath.Join(repo, nodeCIPath))
			if written := readErr == nil; written != (tc.unmet == "") {
				t.Fatalf("CI job scaffolded = %v, want %v; report %+v", written, tc.unmet == "", report)
			}
			if tc.unmet != "" {
				assertUnmet(t, report, tc.unmet)
				return
			}
			if problems := unrunnableNodeSteps(t, string(data), repo); len(problems) > 0 {
				t.Fatalf("the scaffolded job cannot pass here: %v\n%s", problems, data)
			}
			assertJobRuns(t, string(data), tc.runs, tc.absent)
		})
	}
}

// assertJobRuns checks the job runs every command in runs and none in absent.
func assertJobRuns(t *testing.T, body string, runs, absent []string) {
	t.Helper()
	var lines []string
	for _, run := range workflowRunSteps(t, body) {
		lines = append(lines, strings.Split(strings.TrimSpace(run), "\n")...)
	}
	for _, want := range runs {
		if !slices.Contains(lines, want) {
			t.Errorf("the job does not run %q:\n%s", want, body)
		}
	}
	for _, unwanted := range absent {
		if slices.Contains(lines, unwanted) {
			t.Errorf("the job runs %q:\n%s", unwanted, body)
		}
	}
}

func assertUnmet(t *testing.T, report *flavor.ApplyReport, fragment string) {
	t.Helper()
	for _, entry := range report.UnmetTemplates {
		if strings.HasPrefix(entry, nodeCIPath+": ") && strings.Contains(entry, fragment) {
			return
		}
	}
	t.Fatalf("want %s reported unmet with %q, got %v", nodeCIPath, fragment, report.UnmetTemplates)
}

// namedNodeCICase returns the named case.
func namedNodeCICase(t *testing.T, name string) nodeCICase {
	t.Helper()
	cases := nodeCICases()
	i := slices.IndexFunc(cases, func(tc nodeCICase) bool { return tc.name == name })
	if i < 0 {
		t.Fatalf("no case named %s", name)
	}
	return cases[i]
}

// The check above is only as good as its ability to fail. Replayed against each manager's job
// as the template renders it, it flags every repository that job cannot pass in, including the
// npm job in a pnpm project (the body flavor apply once wrote there) and a Yarn 1 install in a
// Yarn 4 project, and passes the repository the job is for.
func TestUnrunnableNodeStepsCatchesTheJobWhereItCannotPass(t *testing.T) {
	for _, check := range []struct {
		node   templates.NodeContext
		passes string
		fails  []string
	}{
		{templates.NodeContext{}, "npm-project", []string{"pnpm-lock-only", "npm-init-placeholder", "shrinkwrap-only", "ignored-lockfile", "yarn-declared-npm-lock"}},
		{templates.NodeContext{Manager: "pnpm"}, "pnpm-lock-only", []string{"npm-project", "yarn-classic-lock-only", "yarn-declared-npm-lock"}},
		{templates.NodeContext{Manager: "yarn", Lint: true}, "yarn-classic-lock-only", []string{"yarn-berry-declared", "yarn-berry-yarnpath", "pnpm-lock-only"}},
		{templates.NodeContext{Manager: "yarn", YarnBerry: true}, "yarn-berry-declared", []string{"yarn-classic-lock-only", "npm-project"}},
		{templates.NodeContext{Manager: "bun"}, "bun-lock", []string{"npm-project", "pnpm-declared", "npm-init-placeholder"}},
	} {
		body, err := templates.RenderFile("node/ci-node.yml.tmpl", templates.Context{RepoName: "widget", Owner: "acme", Node: check.node})
		if err != nil {
			t.Fatalf("render %+v: %v", check.node, err)
		}
		for _, name := range check.fails {
			if problems := unrunnableNodeSteps(t, body, namedNodeCICase(t, name).repo(t)); len(problems) == 0 {
				t.Errorf("%+v in %s: the check passed a job that fails there", check.node, name)
			}
		}
		if problems := unrunnableNodeSteps(t, body, namedNodeCICase(t, check.passes).repo(t)); len(problems) > 0 {
			t.Errorf("%+v in %s: the check rejected a job that passes: %v", check.node, check.passes, problems)
		}
	}
	// Boundary: a command the check does not model is a finding, not a pass, and so is a Yarn
	// --if-present, which Yarn does not have.
	repo := namedNodeCICase(t, "yarn-classic-lock-only").repo(t)
	for _, run := range []string{"deno task test", "yarn run --if-present lint"} {
		unknown := "jobs:\n  test:\n    steps:\n      - uses: actions/setup-node@v4\n      - run: npm install --global corepack@latest\n      - run: corepack enable yarn\n      - run: " + run + "\n"
		if problems := unrunnableNodeSteps(t, unknown, repo); len(problems) != 1 {
			t.Errorf("%q: want one finding, got %v", run, problems)
		}
	}
}

// Boundary: --force replaces existing files, never with a job that cannot pass. An existing
// workflow in a pnpm project whose lockfile is missing stays exactly as it was.
func TestApplyFlavor_Boundary_ForceNeverWritesAnUnrunnableNodeJob(t *testing.T) {
	own := "name: CI\non: push\njobs:\n  test:\n    runs-on: ubuntu-26.04\n    steps:\n      - run: pnpm test\n"
	files := map[string]string{"package.json": `{"packageManager": "pnpm@10.0.0", "scripts": {"test": "vitest"}}`, "package-lock.json": npmLock, nodeCIPath: own}
	repo := gitRepoWithFiles(t, files)
	report, err := flavor.ApplyFlavor(t.Context(), repo, "typescript-node", true)
	if err != nil || len(report.Errors) > 0 {
		t.Fatalf("apply --force: err %v, recorded %v", err, report.Errors)
	}
	data, err := os.ReadFile(filepath.Join(repo, nodeCIPath))
	if err != nil || string(data) != own {
		t.Fatalf("--force replaced the repository's workflow: err %v\n%s", err, data)
	}
	assertUnmet(t, report, "no pnpm-lock.yaml")
}
