apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: praetor-system

resources:
  - ../helm/praetor

commonLabels:
  app.kubernetes.io/part-of: cordanaLLM
  app.kubernetes.io/managed-by: argocd
