// SPDX-FileCopyrightText: 2026 Lusoris <lusoris@proton.me>
//
// SPDX-License-Identifier: EUPL-1.2

// Code generated by internal/clientschema/typegen from the vendored schemas of codex-hooks; DO NOT EDIT.
//
// Source: openai/codex at rust-v0.162.0 (Apache-2.0), 23 files, digest 7f733579bf6682b9.
// Regenerate: go generate ./internal/clientschema

package codexhook

// BlockDecisionWire is generated from the vendored schema.
type BlockDecisionWire string

const (
	BlockDecisionWireBlock BlockDecisionWire = "block"
)

// InterruptCommandInput is generated from the vendored schema.
type InterruptCommandInput struct {
	Cwd            string         `json:"cwd"`
	HookEventName  string         `json:"hook_event_name"` // always "Interrupt"
	Model          string         `json:"model"`
	PermissionMode string         `json:"permission_mode"`
	SessionId      string         `json:"session_id"`
	TranscriptPath NullableString `json:"transcript_path"`
	TurnId         string         `json:"turn_id"` // Codex extension: expose the active turn id to internal turn-scoped hooks.
}

// InterruptCommandOutput is generated from the vendored schema.
type InterruptCommandOutput struct {
	SystemMessage *string `json:"systemMessage,omitempty"`
}

// NullableString is generated from the vendored schema.
type NullableString = *string

// PermissionRequestBehaviorWire is generated from the vendored schema.
type PermissionRequestBehaviorWire string

const (
	PermissionRequestBehaviorWireAllow PermissionRequestBehaviorWire = "allow"
	PermissionRequestBehaviorWireDeny  PermissionRequestBehaviorWire = "deny"
)

// PermissionRequestCommandInput is generated from the vendored schema.
type PermissionRequestCommandInput struct {
	AgentId        *string        `json:"agent_id,omitempty"`
	AgentType      *string        `json:"agent_type,omitempty"`
	Cwd            string         `json:"cwd"`
	HookEventName  string         `json:"hook_event_name"` // always "PermissionRequest"
	Model          string         `json:"model"`
	PermissionMode string         `json:"permission_mode"`
	SessionId      string         `json:"session_id"`
	ToolInput      any            `json:"tool_input"`
	ToolName       string         `json:"tool_name"`
	TranscriptPath NullableString `json:"transcript_path"`
	TurnId         string         `json:"turn_id"` // Codex extension: expose the active turn id to internal turn-scoped hooks.
}

// PermissionRequestCommandOutput is generated from the vendored schema.
type PermissionRequestCommandOutput struct {
	Continue           *bool                                    `json:"continue,omitempty"`
	HookSpecificOutput *PermissionRequestHookSpecificOutputWire `json:"hookSpecificOutput,omitempty"`
	StopReason         *string                                  `json:"stopReason,omitempty"`
	SuppressOutput     *bool                                    `json:"suppressOutput,omitempty"`
	SystemMessage      *string                                  `json:"systemMessage,omitempty"`
}

// PermissionRequestDecisionWire is generated from the vendored schema.
type PermissionRequestDecisionWire struct {
	Behavior           PermissionRequestBehaviorWire `json:"behavior"`
	Interrupt          *bool                         `json:"interrupt,omitempty"` // Reserved for future short-circuiting semantics.
	Message            *string                       `json:"message,omitempty"`
	UpdatedInput       any                           `json:"updatedInput,omitempty"`       // Reserved for a future input-rewrite capability.
	UpdatedPermissions any                           `json:"updatedPermissions,omitempty"` // Reserved for a future permission-rewrite capability.
}

// PermissionRequestHookSpecificOutputWire is generated from the vendored schema.
type PermissionRequestHookSpecificOutputWire struct {
	Decision      *PermissionRequestDecisionWire `json:"decision,omitempty"`
	HookEventName string                         `json:"hookEventName"` // always "PermissionRequest"
}

// PostCompactCommandInput is generated from the vendored schema.
type PostCompactCommandInput struct {
	AgentId        *string        `json:"agent_id,omitempty"`
	AgentType      *string        `json:"agent_type,omitempty"`
	Cwd            string         `json:"cwd"`
	HookEventName  string         `json:"hook_event_name"` // always "PostCompact"
	Model          string         `json:"model"`
	SessionId      string         `json:"session_id"`
	TranscriptPath NullableString `json:"transcript_path"`
	Trigger        string         `json:"trigger"`
	TurnId         string         `json:"turn_id"` // Codex extension: expose the active turn id to internal turn-scoped hooks.
}

// PostCompactCommandOutput is generated from the vendored schema.
type PostCompactCommandOutput struct {
	Continue       *bool   `json:"continue,omitempty"`
	StopReason     *string `json:"stopReason,omitempty"`
	SuppressOutput *bool   `json:"suppressOutput,omitempty"`
	SystemMessage  *string `json:"systemMessage,omitempty"`
}

// PostToolUseCommandInput is generated from the vendored schema.
type PostToolUseCommandInput struct {
	AgentId        *string        `json:"agent_id,omitempty"`
	AgentType      *string        `json:"agent_type,omitempty"`
	Cwd            string         `json:"cwd"`
	HookEventName  string         `json:"hook_event_name"` // always "PostToolUse"
	Model          string         `json:"model"`
	PermissionMode string         `json:"permission_mode"`
	SessionId      string         `json:"session_id"`
	ToolInput      any            `json:"tool_input"`
	ToolName       string         `json:"tool_name"`
	ToolResponse   any            `json:"tool_response"`
	ToolUseId      string         `json:"tool_use_id"`
	TranscriptPath NullableString `json:"transcript_path"`
	TurnId         string         `json:"turn_id"` // Codex extension: expose the active turn id to internal turn-scoped hooks.
}

// PostToolUseCommandOutput is generated from the vendored schema.
type PostToolUseCommandOutput struct {
	Continue           *bool                              `json:"continue,omitempty"`
	Decision           *BlockDecisionWire                 `json:"decision,omitempty"`
	HookSpecificOutput *PostToolUseHookSpecificOutputWire `json:"hookSpecificOutput,omitempty"`
	Reason             *string                            `json:"reason,omitempty"`
	StopReason         *string                            `json:"stopReason,omitempty"`
	SuppressOutput     *bool                              `json:"suppressOutput,omitempty"`
	SystemMessage      *string                            `json:"systemMessage,omitempty"`
}

// PostToolUseHookSpecificOutputWire is generated from the vendored schema.
type PostToolUseHookSpecificOutputWire struct {
	AdditionalContext    *string `json:"additionalContext,omitempty"`
	HookEventName        string  `json:"hookEventName"` // always "PostToolUse"
	UpdatedMCPToolOutput any     `json:"updatedMCPToolOutput,omitempty"`
}

// PreCompactCommandInput is generated from the vendored schema.
type PreCompactCommandInput struct {
	AgentId        *string        `json:"agent_id,omitempty"`
	AgentType      *string        `json:"agent_type,omitempty"`
	Cwd            string         `json:"cwd"`
	HookEventName  string         `json:"hook_event_name"` // always "PreCompact"
	Model          string         `json:"model"`
	SessionId      string         `json:"session_id"`
	TranscriptPath NullableString `json:"transcript_path"`
	Trigger        string         `json:"trigger"`
	TurnId         string         `json:"turn_id"` // Codex extension: expose the active turn id to internal turn-scoped hooks.
}

// PreCompactCommandOutput is generated from the vendored schema.
type PreCompactCommandOutput struct {
	Continue       *bool   `json:"continue,omitempty"`
	StopReason     *string `json:"stopReason,omitempty"`
	SuppressOutput *bool   `json:"suppressOutput,omitempty"`
	SystemMessage  *string `json:"systemMessage,omitempty"`
}

// PreToolUseCommandInput is generated from the vendored schema.
type PreToolUseCommandInput struct {
	AgentId        *string        `json:"agent_id,omitempty"`
	AgentType      *string        `json:"agent_type,omitempty"`
	Cwd            string         `json:"cwd"`
	HookEventName  string         `json:"hook_event_name"` // always "PreToolUse"
	Model          string         `json:"model"`
	PermissionMode string         `json:"permission_mode"`
	SessionId      string         `json:"session_id"`
	ToolInput      any            `json:"tool_input"`
	ToolName       string         `json:"tool_name"`
	ToolUseId      string         `json:"tool_use_id"`
	TranscriptPath NullableString `json:"transcript_path"`
	TurnId         string         `json:"turn_id"` // Codex extension: expose the active turn id to internal turn-scoped hooks.
}

// PreToolUseCommandOutput is generated from the vendored schema.
type PreToolUseCommandOutput struct {
	Continue           *bool                             `json:"continue,omitempty"`
	Decision           *PreToolUseDecisionWire           `json:"decision,omitempty"`
	HookSpecificOutput *PreToolUseHookSpecificOutputWire `json:"hookSpecificOutput,omitempty"`
	Reason             *string                           `json:"reason,omitempty"`
	StopReason         *string                           `json:"stopReason,omitempty"`
	SuppressOutput     *bool                             `json:"suppressOutput,omitempty"`
	SystemMessage      *string                           `json:"systemMessage,omitempty"`
}

// PreToolUseDecisionWire is generated from the vendored schema.
type PreToolUseDecisionWire string

const (
	PreToolUseDecisionWireApprove PreToolUseDecisionWire = "approve"
	PreToolUseDecisionWireBlock   PreToolUseDecisionWire = "block"
)

// PreToolUseHookSpecificOutputWire is generated from the vendored schema.
type PreToolUseHookSpecificOutputWire struct {
	AdditionalContext        *string                           `json:"additionalContext,omitempty"`
	HookEventName            string                            `json:"hookEventName"` // always "PreToolUse"
	PermissionDecision       *PreToolUsePermissionDecisionWire `json:"permissionDecision,omitempty"`
	PermissionDecisionReason *string                           `json:"permissionDecisionReason,omitempty"`
	UpdatedInput             any                               `json:"updatedInput,omitempty"`
}

// PreToolUsePermissionDecisionWire is generated from the vendored schema.
type PreToolUsePermissionDecisionWire string

const (
	PreToolUsePermissionDecisionWireAllow PreToolUsePermissionDecisionWire = "allow"
	PreToolUsePermissionDecisionWireDeny  PreToolUsePermissionDecisionWire = "deny"
	PreToolUsePermissionDecisionWireAsk   PreToolUsePermissionDecisionWire = "ask"
)

// SessionEndCommandInput is generated from the vendored schema.
type SessionEndCommandInput struct {
	Cwd            string         `json:"cwd"`
	HookEventName  string         `json:"hook_event_name"` // always "SessionEnd"
	Reason         string         `json:"reason"`          // always "other"
	SessionId      string         `json:"session_id"`
	TranscriptPath NullableString `json:"transcript_path"`
}

// SessionStartCommandInput is generated from the vendored schema.
type SessionStartCommandInput struct {
	Cwd            string         `json:"cwd"`
	HookEventName  string         `json:"hook_event_name"` // always "SessionStart"
	Model          string         `json:"model"`
	PermissionMode string         `json:"permission_mode"`
	SessionId      string         `json:"session_id"`
	Source         string         `json:"source"`
	TranscriptPath NullableString `json:"transcript_path"`
}

// SessionStartCommandOutput is generated from the vendored schema.
type SessionStartCommandOutput struct {
	Continue           *bool                               `json:"continue,omitempty"`
	HookSpecificOutput *SessionStartHookSpecificOutputWire `json:"hookSpecificOutput,omitempty"`
	StopReason         *string                             `json:"stopReason,omitempty"`
	SuppressOutput     *bool                               `json:"suppressOutput,omitempty"`
	SystemMessage      *string                             `json:"systemMessage,omitempty"`
}

// SessionStartHookSpecificOutputWire is generated from the vendored schema.
type SessionStartHookSpecificOutputWire struct {
	AdditionalContext *string `json:"additionalContext,omitempty"`
	HookEventName     string  `json:"hookEventName"` // always "SessionStart"
}

// StopCommandInput is generated from the vendored schema.
type StopCommandInput struct {
	Cwd                  string         `json:"cwd"`
	HookEventName        string         `json:"hook_event_name"` // always "Stop"
	LastAssistantMessage NullableString `json:"last_assistant_message"`
	Model                string         `json:"model"`
	PermissionMode       string         `json:"permission_mode"`
	SessionId            string         `json:"session_id"`
	StopHookActive       bool           `json:"stop_hook_active"`
	TranscriptPath       NullableString `json:"transcript_path"`
	TurnId               string         `json:"turn_id"` // Codex extension: expose the active turn id to internal turn-scoped hooks.
}

// StopCommandOutput is generated from the vendored schema.
type StopCommandOutput struct {
	Continue       *bool              `json:"continue,omitempty"`
	Decision       *BlockDecisionWire `json:"decision,omitempty"`
	Reason         *string            `json:"reason,omitempty"` // Claude requires `reason` when `decision` is `block`; we enforce that semantic rule during output par...
	StopReason     *string            `json:"stopReason,omitempty"`
	SuppressOutput *bool              `json:"suppressOutput,omitempty"`
	SystemMessage  *string            `json:"systemMessage,omitempty"`
}

// SubagentStartCommandInput is generated from the vendored schema.
type SubagentStartCommandInput struct {
	AgentId        string         `json:"agent_id"`
	AgentType      string         `json:"agent_type"`
	Cwd            string         `json:"cwd"`
	HookEventName  string         `json:"hook_event_name"` // always "SubagentStart"
	Model          string         `json:"model"`
	PermissionMode string         `json:"permission_mode"`
	SessionId      string         `json:"session_id"`
	TranscriptPath NullableString `json:"transcript_path"`
	TurnId         string         `json:"turn_id"` // Codex extension: expose the active turn id to internal turn-scoped hooks.
}

// SubagentStartCommandOutput is generated from the vendored schema.
type SubagentStartCommandOutput struct {
	Continue           *bool                                `json:"continue,omitempty"`
	HookSpecificOutput *SubagentStartHookSpecificOutputWire `json:"hookSpecificOutput,omitempty"`
	StopReason         *string                              `json:"stopReason,omitempty"`
	SuppressOutput     *bool                                `json:"suppressOutput,omitempty"`
	SystemMessage      *string                              `json:"systemMessage,omitempty"`
}

// SubagentStartHookSpecificOutputWire is generated from the vendored schema.
type SubagentStartHookSpecificOutputWire struct {
	AdditionalContext *string `json:"additionalContext,omitempty"`
	HookEventName     string  `json:"hookEventName"` // always "SubagentStart"
}

// SubagentStopCommandInput is generated from the vendored schema.
type SubagentStopCommandInput struct {
	AgentId              string         `json:"agent_id"`
	AgentTranscriptPath  NullableString `json:"agent_transcript_path"`
	AgentType            string         `json:"agent_type"`
	Cwd                  string         `json:"cwd"`
	HookEventName        string         `json:"hook_event_name"` // always "SubagentStop"
	LastAssistantMessage NullableString `json:"last_assistant_message"`
	Model                string         `json:"model"`
	PermissionMode       string         `json:"permission_mode"`
	SessionId            string         `json:"session_id"`
	StopHookActive       bool           `json:"stop_hook_active"`
	TranscriptPath       NullableString `json:"transcript_path"`
	TurnId               string         `json:"turn_id"` // Codex extension: expose the active turn id to internal turn-scoped hooks.
}

// SubagentStopCommandOutput is generated from the vendored schema.
type SubagentStopCommandOutput struct {
	Continue       *bool              `json:"continue,omitempty"`
	Decision       *BlockDecisionWire `json:"decision,omitempty"`
	Reason         *string            `json:"reason,omitempty"` // Claude requires `reason` when `decision` is `block`; we enforce that semantic rule during output par...
	StopReason     *string            `json:"stopReason,omitempty"`
	SuppressOutput *bool              `json:"suppressOutput,omitempty"`
	SystemMessage  *string            `json:"systemMessage,omitempty"`
}

// UserPromptSubmitCommandInput is generated from the vendored schema.
type UserPromptSubmitCommandInput struct {
	AgentId        *string        `json:"agent_id,omitempty"`
	AgentType      *string        `json:"agent_type,omitempty"`
	Cwd            string         `json:"cwd"`
	HookEventName  string         `json:"hook_event_name"` // always "UserPromptSubmit"
	Model          string         `json:"model"`
	PermissionMode string         `json:"permission_mode"`
	Prompt         string         `json:"prompt"`
	SessionId      string         `json:"session_id"`
	TranscriptPath NullableString `json:"transcript_path"`
	TurnId         string         `json:"turn_id"` // Codex extension: expose the active turn id to internal turn-scoped hooks.
}

// UserPromptSubmitCommandOutput is generated from the vendored schema.
type UserPromptSubmitCommandOutput struct {
	Continue           *bool                                   `json:"continue,omitempty"`
	Decision           *BlockDecisionWire                      `json:"decision,omitempty"`
	HookSpecificOutput *UserPromptSubmitHookSpecificOutputWire `json:"hookSpecificOutput,omitempty"`
	Reason             *string                                 `json:"reason,omitempty"`
	StopReason         *string                                 `json:"stopReason,omitempty"`
	SuppressOutput     *bool                                   `json:"suppressOutput,omitempty"`
	SystemMessage      *string                                 `json:"systemMessage,omitempty"`
}

// UserPromptSubmitHookSpecificOutputWire is generated from the vendored schema.
type UserPromptSubmitHookSpecificOutputWire struct {
	AdditionalContext *string `json:"additionalContext,omitempty"`
	HookEventName     string  `json:"hookEventName"` // always "UserPromptSubmit"
}
