// SPDX-FileCopyrightText: 2026 Lusoris <lusoris@proton.me>
//
// SPDX-License-Identifier: EUPL-1.2

// Code generated by internal/clientschema/typegen from the vendored schemas of mcp-protocol; DO NOT EDIT.
//
// Source: modelcontextprotocol/modelcontextprotocol at 2025-11-25 (MIT), 1 files, digest 139acc5e66e8069a.
// Regenerate: go generate ./internal/clientschema

package mcpwire

import "encoding/json"

// Annotations is generated from the vendored schema: Optional annotations for the client.
type Annotations struct {
	Audience     []Role   `json:"audience,omitempty"`     // Describes who the intended audience of this object or data is.
	LastModified *string  `json:"lastModified,omitempty"` // The moment the resource was last modified, as an ISO 8601 formatted string.
	Priority     *float64 `json:"priority,omitempty"`     // Describes how important this data is for operating the server.
}

// CallToolRequestParams is generated from the vendored schema: Parameters for a `tools/call` request.
type CallToolRequestParams struct {
	Meta      *CallToolRequestParamsMeta `json:"_meta,omitempty"`     // See [General fields: `_meta`](/specification/2025-11-25/basic/index#meta) for notes on `_meta` usage...
	Arguments map[string]any             `json:"arguments,omitempty"` // Arguments to use for the tool call.
	Name      string                     `json:"name"`                // The name of the tool.
	Task      *TaskMetadata              `json:"task,omitempty"`      // If specified, the caller is requesting task-augmented execution for this request.
}

// CallToolRequestParamsMeta is generated from the vendored schema: See [General fields: `_meta`](/specification/2025-11-25/basic/index#meta) for notes on `_meta` usage...
type CallToolRequestParamsMeta struct {
	ProgressToken *ProgressToken `json:"progressToken,omitempty"` // If specified, the caller is requesting out-of-band progress notifications for this request (as repre...
}

// CallToolResult is generated from the vendored schema: The server's response to a tool call.
type CallToolResult struct {
	Meta              map[string]any `json:"_meta,omitempty"`             // See [General fields: `_meta`](/specification/2025-11-25/basic/index#meta) for notes on `_meta` usage...
	Content           []ContentBlock `json:"content"`                     // A list of content objects that represent the unstructured result of the tool call.
	IsError           *bool          `json:"isError,omitempty"`           // Whether the tool call ended in an error.
	StructuredContent map[string]any `json:"structuredContent,omitempty"` // An optional JSON object that represents the structured result of the tool call.
}

// ClientCapabilities is generated from the vendored schema: Capabilities a client may support.
type ClientCapabilities struct {
	Elicitation  *ClientCapabilitiesElicitation                 `json:"elicitation,omitempty"`  // Present if the client supports elicitation from the server.
	Experimental map[string]ClientCapabilitiesExperimentalValue `json:"experimental,omitempty"` // Experimental, non-standard capabilities that the client supports.
	Roots        *ClientCapabilitiesRoots                       `json:"roots,omitempty"`        // Present if the client supports listing roots.
	Sampling     *ClientCapabilitiesSampling                    `json:"sampling,omitempty"`     // Present if the client supports sampling from an LLM.
	Tasks        *ClientCapabilitiesTasks                       `json:"tasks,omitempty"`        // Present if the client supports task-augmented requests.
}

// ClientCapabilitiesElicitation is generated from the vendored schema: Present if the client supports elicitation from the server.
type ClientCapabilitiesElicitation struct {
	Form *ClientCapabilitiesElicitationForm `json:"form,omitempty"`
	Url  *ClientCapabilitiesElicitationUrl  `json:"url,omitempty"`
}

// ClientCapabilitiesElicitationForm is generated from the vendored schema.
type ClientCapabilitiesElicitationForm struct {
}

// ClientCapabilitiesElicitationUrl is generated from the vendored schema.
type ClientCapabilitiesElicitationUrl struct {
}

// ClientCapabilitiesExperimentalValue is generated from the vendored schema.
type ClientCapabilitiesExperimentalValue struct {
}

// ClientCapabilitiesRoots is generated from the vendored schema: Present if the client supports listing roots.
type ClientCapabilitiesRoots struct {
	ListChanged *bool `json:"listChanged,omitempty"` // Whether the client supports notifications for changes to the roots list.
}

// ClientCapabilitiesSampling is generated from the vendored schema: Present if the client supports sampling from an LLM.
type ClientCapabilitiesSampling struct {
	Context *ClientCapabilitiesSamplingContext `json:"context,omitempty"` // Whether the client supports context inclusion via includeContext parameter.
	Tools   *ClientCapabilitiesSamplingTools   `json:"tools,omitempty"`   // Whether the client supports tool use via tools and toolChoice parameters.
}

// ClientCapabilitiesSamplingContext is generated from the vendored schema: Whether the client supports context inclusion via includeContext parameter.
type ClientCapabilitiesSamplingContext struct {
}

// ClientCapabilitiesSamplingTools is generated from the vendored schema: Whether the client supports tool use via tools and toolChoice parameters.
type ClientCapabilitiesSamplingTools struct {
}

// ClientCapabilitiesTasks is generated from the vendored schema: Present if the client supports task-augmented requests.
type ClientCapabilitiesTasks struct {
	Cancel   *ClientCapabilitiesTasksCancel   `json:"cancel,omitempty"`   // Whether this client supports tasks/cancel.
	List     *ClientCapabilitiesTasksList     `json:"list,omitempty"`     // Whether this client supports tasks/list.
	Requests *ClientCapabilitiesTasksRequests `json:"requests,omitempty"` // Specifies which request types can be augmented with tasks.
}

// ClientCapabilitiesTasksCancel is generated from the vendored schema: Whether this client supports tasks/cancel.
type ClientCapabilitiesTasksCancel struct {
}

// ClientCapabilitiesTasksList is generated from the vendored schema: Whether this client supports tasks/list.
type ClientCapabilitiesTasksList struct {
}

// ClientCapabilitiesTasksRequests is generated from the vendored schema: Specifies which request types can be augmented with tasks.
type ClientCapabilitiesTasksRequests struct {
	Elicitation *ClientCapabilitiesTasksRequestsElicitation `json:"elicitation,omitempty"` // Task support for elicitation-related requests.
	Sampling    *ClientCapabilitiesTasksRequestsSampling    `json:"sampling,omitempty"`    // Task support for sampling-related requests.
}

// ClientCapabilitiesTasksRequestsElicitation is generated from the vendored schema: Task support for elicitation-related requests.
type ClientCapabilitiesTasksRequestsElicitation struct {
	Create *ClientCapabilitiesTasksRequestsElicitationCreate `json:"create,omitempty"` // Whether the client supports task-augmented elicitation/create requests.
}

// ClientCapabilitiesTasksRequestsElicitationCreate is generated from the vendored schema: Whether the client supports task-augmented elicitation/create requests.
type ClientCapabilitiesTasksRequestsElicitationCreate struct {
}

// ClientCapabilitiesTasksRequestsSampling is generated from the vendored schema: Task support for sampling-related requests.
type ClientCapabilitiesTasksRequestsSampling struct {
	CreateMessage *ClientCapabilitiesTasksRequestsSamplingCreateMessage `json:"createMessage,omitempty"` // Whether the client supports task-augmented sampling/createMessage requests.
}

// ClientCapabilitiesTasksRequestsSamplingCreateMessage is generated from the vendored schema: Whether the client supports task-augmented sampling/createMessage requests.
type ClientCapabilitiesTasksRequestsSamplingCreateMessage struct {
}

// ContentBlock is generated from the vendored schema.
type ContentBlock = json.RawMessage

// Error is generated from the vendored schema.
type Error struct {
	Code    int64  `json:"code"`           // The error type that occurred.
	Data    any    `json:"data,omitempty"` // Additional information about the error.
	Message string `json:"message"`        // A short description of the error.
}

// Icon is generated from the vendored schema: An optionally-sized icon that can be displayed in a user interface.
type Icon struct {
	MimeType *string  `json:"mimeType,omitempty"` // Optional MIME type override if the source MIME type is missing or generic.
	Sizes    []string `json:"sizes,omitempty"`    // Optional array of strings that specify sizes at which the icon can be used.
	Src      string   `json:"src"`                // A standard URI pointing to an icon resource.
	Theme    *string  `json:"theme,omitempty"`    // Optional specifier for the theme this icon is designed for.
}

// Implementation is generated from the vendored schema: Describes the MCP implementation.
type Implementation struct {
	Description *string `json:"description,omitempty"` // An optional human-readable description of what this implementation does.
	Icons       []Icon  `json:"icons,omitempty"`       // Optional set of sized icons that the client can display in a user interface.
	Name        string  `json:"name"`                  // Intended for programmatic or logical use, but used as a display name in past specs or fallback (if t...
	Title       *string `json:"title,omitempty"`       // Intended for UI and end-user contexts — optimized to be human-readable and easily understood, even...
	Version     string  `json:"version"`
	WebsiteUrl  *string `json:"websiteUrl,omitempty"` // An optional URL of the website for this implementation.
}

// InitializeRequestParams is generated from the vendored schema: Parameters for an `initialize` request.
type InitializeRequestParams struct {
	Meta            *InitializeRequestParamsMeta `json:"_meta,omitempty"` // See [General fields: `_meta`](/specification/2025-11-25/basic/index#meta) for notes on `_meta` usage...
	Capabilities    ClientCapabilities           `json:"capabilities"`
	ClientInfo      Implementation               `json:"clientInfo"`
	ProtocolVersion string                       `json:"protocolVersion"` // The latest version of the Model Context Protocol that the client supports.
}

// InitializeRequestParamsMeta is generated from the vendored schema: See [General fields: `_meta`](/specification/2025-11-25/basic/index#meta) for notes on `_meta` usage...
type InitializeRequestParamsMeta struct {
	ProgressToken *ProgressToken `json:"progressToken,omitempty"` // If specified, the caller is requesting out-of-band progress notifications for this request (as repre...
}

// InitializeResult is generated from the vendored schema: After receiving an initialize request from the client, the server sends this response.
type InitializeResult struct {
	Meta            map[string]any     `json:"_meta,omitempty"` // See [General fields: `_meta`](/specification/2025-11-25/basic/index#meta) for notes on `_meta` usage...
	Capabilities    ServerCapabilities `json:"capabilities"`
	Instructions    *string            `json:"instructions,omitempty"` // Instructions describing how to use the server and its features.
	ProtocolVersion string             `json:"protocolVersion"`        // The version of the Model Context Protocol that the server wants to use.
	ServerInfo      Implementation     `json:"serverInfo"`
}

// JSONRPCErrorResponse is generated from the vendored schema: A response to a request that indicates an error occurred.
type JSONRPCErrorResponse struct {
	Error   Error      `json:"error"`
	Id      *RequestId `json:"id,omitempty"`
	Jsonrpc string     `json:"jsonrpc"` // always "2.0"
}

// JSONRPCNotification is generated from the vendored schema: A notification which does not expect a response.
type JSONRPCNotification struct {
	Jsonrpc string         `json:"jsonrpc"` // always "2.0"
	Method  string         `json:"method"`
	Params  map[string]any `json:"params,omitempty"`
}

// JSONRPCRequest is generated from the vendored schema: A request that expects a response.
type JSONRPCRequest struct {
	Id      RequestId      `json:"id"`
	Jsonrpc string         `json:"jsonrpc"` // always "2.0"
	Method  string         `json:"method"`
	Params  map[string]any `json:"params,omitempty"`
}

// JSONRPCResultResponse is generated from the vendored schema: A successful (non-error) response to a request.
type JSONRPCResultResponse struct {
	Id      RequestId `json:"id"`
	Jsonrpc string    `json:"jsonrpc"` // always "2.0"
	Result  Result    `json:"result"`
}

// ListToolsResult is generated from the vendored schema: The server's response to a tools/list request from the client.
type ListToolsResult struct {
	Meta       map[string]any `json:"_meta,omitempty"`      // See [General fields: `_meta`](/specification/2025-11-25/basic/index#meta) for notes on `_meta` usage...
	NextCursor *string        `json:"nextCursor,omitempty"` // An opaque token representing the pagination position after the last returned result.
	Tools      []Tool         `json:"tools"`
}

// ProgressToken is generated from the vendored schema: A progress token, used to associate progress notifications with the original request.
type ProgressToken = any

// RequestId is generated from the vendored schema: A uniquely identifying ID for a request in JSON-RPC.
type RequestId = any

// Result is generated from the vendored schema.
type Result struct {
	Meta map[string]any `json:"_meta,omitempty"` // See [General fields: `_meta`](/specification/2025-11-25/basic/index#meta) for notes on `_meta` usage...
}

// Role is generated from the vendored schema: The sender or recipient of messages and data in a conversation.
type Role string

const (
	RoleAssistant Role = "assistant"
	RoleUser      Role = "user"
)

// ServerCapabilities is generated from the vendored schema: Capabilities that a server may support.
type ServerCapabilities struct {
	Completions  *ServerCapabilitiesCompletions                 `json:"completions,omitempty"`  // Present if the server supports argument autocompletion suggestions.
	Experimental map[string]ServerCapabilitiesExperimentalValue `json:"experimental,omitempty"` // Experimental, non-standard capabilities that the server supports.
	Logging      *ServerCapabilitiesLogging                     `json:"logging,omitempty"`      // Present if the server supports sending log messages to the client.
	Prompts      *ServerCapabilitiesPrompts                     `json:"prompts,omitempty"`      // Present if the server offers any prompt templates.
	Resources    *ServerCapabilitiesResources                   `json:"resources,omitempty"`    // Present if the server offers any resources to read.
	Tasks        *ServerCapabilitiesTasks                       `json:"tasks,omitempty"`        // Present if the server supports task-augmented requests.
	Tools        *ServerCapabilitiesTools                       `json:"tools,omitempty"`        // Present if the server offers any tools to call.
}

// ServerCapabilitiesCompletions is generated from the vendored schema: Present if the server supports argument autocompletion suggestions.
type ServerCapabilitiesCompletions struct {
}

// ServerCapabilitiesExperimentalValue is generated from the vendored schema.
type ServerCapabilitiesExperimentalValue struct {
}

// ServerCapabilitiesLogging is generated from the vendored schema: Present if the server supports sending log messages to the client.
type ServerCapabilitiesLogging struct {
}

// ServerCapabilitiesPrompts is generated from the vendored schema: Present if the server offers any prompt templates.
type ServerCapabilitiesPrompts struct {
	ListChanged *bool `json:"listChanged,omitempty"` // Whether this server supports notifications for changes to the prompt list.
}

// ServerCapabilitiesResources is generated from the vendored schema: Present if the server offers any resources to read.
type ServerCapabilitiesResources struct {
	ListChanged *bool `json:"listChanged,omitempty"` // Whether this server supports notifications for changes to the resource list.
	Subscribe   *bool `json:"subscribe,omitempty"`   // Whether this server supports subscribing to resource updates.
}

// ServerCapabilitiesTasks is generated from the vendored schema: Present if the server supports task-augmented requests.
type ServerCapabilitiesTasks struct {
	Cancel   *ServerCapabilitiesTasksCancel   `json:"cancel,omitempty"`   // Whether this server supports tasks/cancel.
	List     *ServerCapabilitiesTasksList     `json:"list,omitempty"`     // Whether this server supports tasks/list.
	Requests *ServerCapabilitiesTasksRequests `json:"requests,omitempty"` // Specifies which request types can be augmented with tasks.
}

// ServerCapabilitiesTasksCancel is generated from the vendored schema: Whether this server supports tasks/cancel.
type ServerCapabilitiesTasksCancel struct {
}

// ServerCapabilitiesTasksList is generated from the vendored schema: Whether this server supports tasks/list.
type ServerCapabilitiesTasksList struct {
}

// ServerCapabilitiesTasksRequests is generated from the vendored schema: Specifies which request types can be augmented with tasks.
type ServerCapabilitiesTasksRequests struct {
	Tools *ServerCapabilitiesTasksRequestsTools `json:"tools,omitempty"` // Task support for tool-related requests.
}

// ServerCapabilitiesTasksRequestsTools is generated from the vendored schema: Task support for tool-related requests.
type ServerCapabilitiesTasksRequestsTools struct {
	Call *ServerCapabilitiesTasksRequestsToolsCall `json:"call,omitempty"` // Whether the server supports task-augmented tools/call requests.
}

// ServerCapabilitiesTasksRequestsToolsCall is generated from the vendored schema: Whether the server supports task-augmented tools/call requests.
type ServerCapabilitiesTasksRequestsToolsCall struct {
}

// ServerCapabilitiesTools is generated from the vendored schema: Present if the server offers any tools to call.
type ServerCapabilitiesTools struct {
	ListChanged *bool `json:"listChanged,omitempty"` // Whether this server supports notifications for changes to the tool list.
}

// TaskMetadata is generated from the vendored schema: Metadata for augmenting a request with task execution.
type TaskMetadata struct {
	Ttl *int64 `json:"ttl,omitempty"` // Requested duration in milliseconds to retain task from creation.
}

// TextContent is generated from the vendored schema: Text provided to or from an LLM.
type TextContent struct {
	Meta        map[string]any `json:"_meta,omitempty"`       // See [General fields: `_meta`](/specification/2025-11-25/basic/index#meta) for notes on `_meta` usage...
	Annotations *Annotations   `json:"annotations,omitempty"` // Optional annotations for the client.
	Text        string         `json:"text"`                  // The text content of the message.
	Type        string         `json:"type"`                  // always "text"
}

// Tool is generated from the vendored schema: Definition for a tool the client can call.
type Tool struct {
	Meta         map[string]any    `json:"_meta,omitempty"`        // See [General fields: `_meta`](/specification/2025-11-25/basic/index#meta) for notes on `_meta` usage...
	Annotations  *ToolAnnotations  `json:"annotations,omitempty"`  // Optional additional tool information.
	Description  *string           `json:"description,omitempty"`  // A human-readable description of the tool.
	Execution    *ToolExecution    `json:"execution,omitempty"`    // Execution-related properties for this tool.
	Icons        []Icon            `json:"icons,omitempty"`        // Optional set of sized icons that the client can display in a user interface.
	InputSchema  ToolInputSchema   `json:"inputSchema"`            // A JSON Schema object defining the expected parameters for the tool.
	Name         string            `json:"name"`                   // Intended for programmatic or logical use, but used as a display name in past specs or fallback (if t...
	OutputSchema *ToolOutputSchema `json:"outputSchema,omitempty"` // An optional JSON Schema object defining the structure of the tool's output returned in the structure...
	Title        *string           `json:"title,omitempty"`        // Intended for UI and end-user contexts — optimized to be human-readable and easily understood, even...
}

// ToolAnnotations is generated from the vendored schema: Additional properties describing a Tool to clients.
type ToolAnnotations struct {
	DestructiveHint *bool   `json:"destructiveHint,omitempty"` // If true, the tool may perform destructive updates to its environment.
	IdempotentHint  *bool   `json:"idempotentHint,omitempty"`  // If true, calling the tool repeatedly with the same arguments will have no additional effect on its e...
	OpenWorldHint   *bool   `json:"openWorldHint,omitempty"`   // If true, this tool may interact with an "open world" of external entities.
	ReadOnlyHint    *bool   `json:"readOnlyHint,omitempty"`    // If true, the tool does not modify its environment.
	Title           *string `json:"title,omitempty"`           // A human-readable title for the tool.
}

// ToolExecution is generated from the vendored schema: Execution-related properties for a tool.
type ToolExecution struct {
	TaskSupport *string `json:"taskSupport,omitempty"` // Indicates whether this tool supports task-augmented execution.
}

// ToolInputSchema is generated from the vendored schema: A JSON Schema object defining the expected parameters for the tool.
type ToolInputSchema struct {
	Schema     *string                                   `json:"$schema,omitempty"`
	Properties map[string]ToolInputSchemaPropertiesValue `json:"properties,omitempty"`
	Required   []string                                  `json:"required,omitempty"`
	Type       string                                    `json:"type"` // always "object"
}

// ToolInputSchemaPropertiesValue is generated from the vendored schema.
type ToolInputSchemaPropertiesValue struct {
}

// ToolOutputSchema is generated from the vendored schema: An optional JSON Schema object defining the structure of the tool's output returned in the structure...
type ToolOutputSchema struct {
	Schema     *string                                    `json:"$schema,omitempty"`
	Properties map[string]ToolOutputSchemaPropertiesValue `json:"properties,omitempty"`
	Required   []string                                   `json:"required,omitempty"`
	Type       string                                     `json:"type"` // always "object"
}

// ToolOutputSchemaPropertiesValue is generated from the vendored schema.
type ToolOutputSchemaPropertiesValue struct {
}
