package adopt

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/cordanaLLM/praetor/internal/config"
	"github.com/cordanaLLM/praetor/internal/contextopt"
	"github.com/cordanaLLM/praetor/internal/hisscatalog"
	"github.com/cordanaLLM/praetor/internal/readmegovernance"
	"github.com/cordanaLLM/praetor/internal/util"
)

const (
	makefileName     = "Makefile"
	gitIgnoreFile    = ".gitignore"
	contributingFile = "CONTRIBUTING.md"
	prTemplateFile   = ".github/pull_request_template.md"
	prTemplateUpper  = ".github/PULL_REQUEST_TEMPLATE.md"
	securityFile     = "SECURITY.md"
	adrIndexFile     = "docs/adr/README.md"
	adrTemplateFile  = "docs/adr/0000-template.md"
	readmeFile       = readmegovernance.File
)

// buildMakefile renders the greenfield Makefile. verify-all runs the same gates the
// AGENTS.md harness advertises; the test and build recipes follow detected project markers.
func buildMakefile(plan *VerificationPlan) string {
	return buildMakefileWithSourceGate(plan, verificationRecipePrefix, true)
}

// buildMakefileWith renders the greenfield Makefile with command lines starting with prefix.
func buildMakefileWith(plan *VerificationPlan, prefix string) string {
	return buildMakefileWithSourceGate(plan, prefix, true)
}

func buildMakefileWithSourceGate(plan *VerificationPlan, prefix string, sourceGate bool) string {
	gateTarget, gateRecipe, gatePhony := "", "", ""
	if sourceGate {
		gateTarget = " caveman-sources"
		gateRecipe = "caveman-sources:\n" + util.MakefileCLI("caveman check --configured-sources") + "\n"
		gatePhony = " caveman-sources"
	}
	return "# Generated by Praetor from declared project commands; execution is unverified.\n" +
		util.MakefileCLIVariable +
		".PHONY: all verify-all compile-context compile-context-verify" + gatePhony + " audit build test\n\n" +
		"all: build\n\n" +
		"verify-all: compile-context-verify" + gateTarget + " audit test\n\n" +
		"compile-context:\n" + util.MakefileCLI("compile-context") + "\n" +
		"compile-context-verify:\n" + util.MakefileCLI("compile-context --verify") + "\n" +
		gateRecipe +
		"audit:\n" + util.MakefileCLI("audit") + "\n" +
		"test: build\n" + verificationRecipeWith(plan, plan.Test, prefix) + "\n" +
		"build:\n" + verificationRecipeWith(plan, plan.Build, prefix)
}

func priorSourceGateMakefile(plan *VerificationPlan) string {
	return buildMakefileWithSourceGate(plan, verificationRecipePrefix, false)
}

func reconcileMakefile(ctx context.Context, s *adoptSession) error {
	documentationEnabled, err := documentationEnabledForSession(s)
	if err != nil {
		return fmt.Errorf("resolve documentation facet for Makefile: %w", err)
	}
	full, err := repoFile(s.repoPath, makefileName)
	if err != nil {
		return err
	}
	data, exists, err := contextopt.ObserveSnapshot(ctx, full)
	if err != nil {
		return err
	}
	data, err = reconcileDisabledDocumentationMakefile(ctx, s, full, data, exists, documentationEnabled)
	if err != nil {
		return err
	}
	generated := isReplaceableVerificationMakefile(string(data), s.verification)
	handled, err := reconcileExistingVerificationMakefile(ctx, s, string(data), exists, generated, documentationEnabled)
	if err != nil || handled {
		return err
	}
	replacement, err := verificationMakefileReplacement(s, string(data), exists, generated, documentationEnabled)
	if err != nil {
		return err
	}
	return publishVerificationMakefile(ctx, s, full, data, replacement, exists)
}

func reconcileDisabledDocumentationMakefile(
	ctx context.Context, s *adoptSession, full string, data []byte, exists, documentationEnabled bool,
) ([]byte, error) {
	if documentationEnabled || !exists {
		return data, nil
	}
	cleaned, removed, err := removeDocumentationMakefileBlock(string(data))
	if err != nil || !removed {
		return data, err
	}
	if !s.opts.DryRun {
		if err := contextopt.ReplaceSnapshot(ctx, full, []byte(cleaned), contextopt.ReplaceOptions{
			Expected: data, Exists: true, Mode: filePerm,
		}); err != nil {
			return nil, err
		}
	}
	s.report.recordReconciledAs(makefileName, actionRemove,
		"Removed canonical documentation gate because docs:seo-portal is disabled")
	return []byte(cleaned), nil
}

func publishVerificationMakefile(
	ctx context.Context, s *adoptSession, full string, data []byte, replacement string, exists bool,
) error {
	if !s.opts.DryRun {
		if err := contextopt.ReplaceSnapshot(ctx, full, []byte(replacement), contextopt.ReplaceOptions{
			Expected: data, Exists: exists, Mode: filePerm,
		}); err != nil {
			return err
		}
	}
	if exists {
		s.report.recordReconciledAs(makefileName, actionAppend, "Reconciled declared verification commands; preserved custom recipes")
	} else {
		s.report.recordCreated(makefileName, "Created Makefile from declared project verification commands")
	}
	return nil
}

func verificationMakefileReplacement(
	s *adoptSession, data string, exists, generated, documentationEnabled bool,
) (string, error) {
	replacement := buildMakefile(s.verification)
	if exists && !generated {
		var err error
		replacement, err = appendVerificationTargets(data, s.verification)
		if err != nil {
			return "", err
		}
	}
	if documentationEnabled {
		return mergeDocumentationMakefile(replacement, false)
	}
	return replacement, nil
}

func reconcileExistingVerificationMakefile(
	ctx context.Context, s *adoptSession, data string, exists, generated, documentationEnabled bool,
) (bool, error) {
	if !exists || !mayDefineVerificationTarget(data) || generated {
		return false, nil
	}
	if documentationEnabled {
		return true, reconcileDocumentationMakefile(ctx, s)
	}
	s.report.recordReconciled(makefileName, "Existing verify-all preserved; execution has not been verified by adoption")
	return true, nil
}

func reconcileContributing(ctx context.Context, s *adoptSession) error {
	_, err := s.scaffoldFile(ctx, scaffold{
		rel:      contributingFile,
		perm:     filePerm,
		content:  []byte(buildContributingGuide(s.repoName)),
		created:  "Scaffolded contributor governance guide with HISS & NASA rules",
		verified: "Existing contributor guide verified present",
	})
	return err
}

// reconcilePullRequestTemplate keeps whichever template name the repository already uses and
// compares it with the scaffold like every other preserved file.
func reconcilePullRequestTemplate(ctx context.Context, s *adoptSession) error {
	upper, err := repoFile(s.repoPath, prTemplateUpper)
	if err != nil {
		return err
	}
	rel := prTemplateFile
	if fileExists(upper) {
		rel = prTemplateUpper
	}
	_, err = s.scaffoldFile(ctx, scaffold{
		rel:      rel,
		perm:     filePerm,
		content:  []byte(buildPullRequestTemplate()),
		created:  "Scaffolded pull request template with HISS verification checklist",
		verified: "Existing pull request template verified present",
	})
	return err
}

func reconcileSecurityPolicy(ctx context.Context, s *adoptSession) error {
	_, err := s.scaffoldFile(ctx, scaffold{
		rel:      securityFile,
		perm:     filePerm,
		content:  []byte(buildSecurityPolicy()),
		created:  "Scaffolded security policy and vulnerability disclosure standards",
		verified: "Existing security policy verified present",
	})
	return err
}

func reconcileADR(_ context.Context, s *adoptSession) error {
	index, err := repoFile(s.repoPath, adrIndexFile)
	if err != nil {
		return err
	}
	if fileExists(index) {
		s.report.recordReconciled(adrIndexFile, "Architectural Decision Records directory verified present")
		return nil
	}
	tmpl, err := repoFile(s.repoPath, adrTemplateFile)
	if err != nil {
		return err
	}
	if err := s.write(index, []byte(buildADRIndex()), filePerm); err != nil {
		return err
	}
	if err := s.write(tmpl, []byte(buildADRTemplate()), filePerm); err != nil {
		return err
	}
	s.report.recordCreated(adrIndexFile, "Scaffolded Architectural Decision Records (ADR) directory and template")
	return nil
}

// reconcileReadme refreshes the only README region Praetor owns. A baseline records debt;
// it never certifies that the repository's full verification cascade passed.
func reconcileReadme(ctx context.Context, s *adoptSession) error {
	documentationEnabled, err := documentationEnabledForSession(s)
	if err != nil {
		return fmt.Errorf("resolve documentation facet for README: %w", err)
	}
	full, err := repoFile(s.repoPath, readmeFile)
	if err != nil {
		return err
	}
	data, exists, err := contextopt.ObserveSnapshot(ctx, full)
	if err != nil {
		return err
	}
	if !exists {
		return nil
	}
	state, err := readmeGovernanceState(s, documentationEnabled)
	if err != nil {
		return s.readmeStateError(err)
	}
	content, changed, err := readmegovernance.Reconcile(string(data), state)
	if err != nil || !changed {
		return err
	}
	if err := s.write(full, []byte(content), filePerm); err != nil {
		return err
	}
	s.report.recordReconciled(readmeFile, "Reconciled the marker-owned HISS adoption and verification contract")
	return nil
}

func readmeGovernanceState(s *adoptSession, documentationEnabled bool) (readmegovernance.State, error) {
	state := readmegovernance.State{
		BaselineKnown:        s.report.BaselineStatus == "scanned" || s.report.BaselineStatus == "existing",
		LegacyDebtCount:      s.report.LegacyDebtCount,
		DocumentationEnabled: documentationEnabled,
	}
	var manifest *config.Manifest
	if s.policy != nil {
		manifest = s.policy.Manifest
	}
	if documentationEnabled && manifest == nil {
		return state, fmt.Errorf("reconcile README documentation contract: effective manifest is unavailable")
	}
	owner, name, err := ReadmeIdentity(manifest, documentationEnabled)
	state.RepositoryOwner, state.RepositoryName = owner, name
	state.RepositoryHost = s.identity.forgeHost(owner, name)
	return state, err
}

// ReadmeIdentity returns the manifest identity the README governance block's badges link
// into by absolute URL (readmegovernance.State); adoption and audit both read it here. A
// manifest naming both repository.owner and repository.name returns them. Which forge hosts
// that repository is not the manifest's to say: adoption pairs the identity with the origin
// remote's host only when the remote names exactly that repository (repoIdentity.forgeHost),
// and the HISS badge stays unlinked on any host whose URL shape is unknown. Without both
// fields it returns no identity, or, under the documentation gate, whose badge needs one, an
// error wrapping errReadmeIdentityUnset.
func ReadmeIdentity(manifest *config.Manifest, documentationEnabled bool) (owner, name string, err error) {
	if manifest != nil {
		owner, name = manifest.Repository.Owner, manifest.Repository.Name
	}
	if owner != "" && name != "" {
		return owner, name, nil
	}
	if documentationEnabled {
		return "", "", errReadmeIdentityUnset
	}
	return "", "", nil
}

// errReadmeIdentityUnset: the documentation gate's badges link into the repository, and the
// manifest names none or half of one. Adoption leaves the README alone rather than link to a
// guessed repository.
var errReadmeIdentityUnset = errors.New("the documentation badges need repository.owner and repository.name")

// readmeStateError turns an unset identity into a recorded skip, so an adoption without a
// resolvable identity completes and says what it left undone; any other error fails the step.
func (s *adoptSession) readmeStateError(err error) error {
	if !errors.Is(err, errReadmeIdentityUnset) {
		return err
	}
	s.report.recordSkipped(readmeFile, "Governance block not reconciled: "+err.Error()+" in "+manifestFile+
		"; set them, or the origin remote before a first adoption, and re-run")
	return nil
}

// markdownDocument joins lines into a Markdown file ending in one newline.
//
// The scaffolded governance documents below are an adopter's own files, which the
// adopter's Markdown lint reads, so each line is written within markdownlint's default
// 80-column limit instead of opening the file with a markdownlint-disable MD013 line
// that would also silence the rule for everything the adopter adds (BUG-806).
func markdownDocument(lines ...string) string {
	return strings.Join(lines, "\n") + "\n"
}

func buildContributingGuide(repoName string) string {
	return markdownDocument(
		"# Contributing to "+repoName,
		"",
		"Thank you for contributing! This repository adheres strictly to the",
		"**High-Integrity Systems Standard (HISS)** and modernized **NASA JPL",
		"Power-of-10** rules.",
		"",
		"## Core Directives & Verification",
		"",
		"All changes must pass local verification before submitting:",
		"",
		"```bash",
		"make verify-all",
		"```",
		"",
		"### Modernized NASA JPL Power-of-10 Rules",
		"",
		"1. **Simple Control Flow (HISS-01)**: Recursion is strictly banned; call graph",
		"   must be an acyclic DAG; zero `goto`.",
		"2. **Bounded Loops (HISS-02)**: All loops must have a statically verifiable",
		"   scalar upper bound. Network and disk I/O require `context.Context` timeout.",
		"3. **Deterministic Memory (HISS-03)**: Zero dynamic heap allocations",
		"   (`malloc` / `free`) in hot simulation or rendering loops.",
		"4. **Function Length Cap (HISS-04)**: No function may exceed",
		"   **60 lines of code** ($\\le 60$ LOC).",
		"5. **Assertion Density (HISS-15)**: Functions must assert preconditions, state",
		"   invariants, and postconditions.",
		"6. **Data Scope**: Variables must be declared at the smallest possible scope.",
		"7. **Checked Errors (HISS-07)**: Check return values of all non-void functions;",
		"   zero `.unwrap()` or unchecked errors.",
		"8. **Static Execution (HISS-08)**: Dynamic code evaluation (`eval` / `exec`)",
		"   and banned unsafe libc calls (`gets` / `strcpy` / `sprintf`) are prohibited.",
		"9. **Pointer Safety (HISS-09)**: Pointer arithmetic must be bounded; all",
		"   `unsafe` blocks require `// SAFETY:` justifications.",
		"10. **Zero-Warning Hygiene (HISS-10)**: Zero compiler, linter, or formatting",
		"    warnings tolerated across all builds.",
		"",
		"### 3D Testing Discipline (HISS-15)",
		"",
		"Every public function requires:",
		"",
		"- **Positive tests**: Expected valid operational inputs.",
		"- **Negative tests**: Invalid inputs, expected error returns.",
		"- **Boundary tests**: Zero, one, max limits, off-by-one bounds.",
		"",
		"### Commit Messages",
		"",
		"We enforce Conventional Commits:",
		"",
		"- `feat:` New features",
		"- `fix:` Bug fixes",
		"- `chore:` Maintenance and governance",
		"- `feat!:` / `fix!:` Breaking API changes (must include `Migration:` footer)",
	)
}

func buildPullRequestTemplate() string {
	return markdownDocument(
		"# Pull Request",
		"",
		"## Description",
		"",
		"<!-- Summarize the changes and their architectural rationale. -->",
		"",
		"## Pre-Merge Verification Checklist",
		"",
		"- [ ] Local verification passed: `make verify-all`",
		"- [ ] No new HISS / NASA Power-of-10 infractions (all new/modified functions",
		"  $\\le 60$ LOC)",
		"- [ ] 3D Tests included (Positive, Negative, Boundary) for public APIs",
		"- [ ] Agent contexts in sync: `standardsctl compile-context --verify`",
		"- [ ] Commit messages adhere to Conventional Commits format",
	)
}

func buildSecurityPolicy() string {
	return markdownDocument(
		"# Security Policy",
		"",
		"## Supported Versions",
		"",
		"Only the latest release and current default branch receive security updates.",
		"",
		"## Reporting a Vulnerability",
		"",
		"Please report security vulnerabilities privately to the maintainers rather",
		"than opening a public issue. Reports are investigated promptly under",
		"responsible disclosure guidelines.",
	)
}

// buildADRIndex renders the ADR index. It cites HISS-14 by the catalog's own title
// (hisscatalog.LookupRule): the index once credited HISS-14 with an "immutable numbering
// lattice" that no rule states (BUG-779).
func buildADRIndex() string {
	appendOnly := "HISS-14"
	if rule, ok := hisscatalog.LookupRule(appendOnly); ok {
		appendOnly = rule.Reference()
	}
	return markdownDocument(
		"# Architectural Decision Records (ADRs)",
		"",
		"This directory documents key architectural decisions. Records are append-only",
		"like public APIs under "+appendOnly+".",
		"An accepted record keeps its number and text; a changed decision is a new",
		"record that supersedes it.",
		"",
		"| Number | Date | Title | Status |",
		"| :--- | :--- | :--- | :--- |",
		"| [0000](0000-template.md) | 2026-09-11 | ADR template | Accepted |",
	)
}

func buildADRTemplate() string {
	return `# ADR-0000: Title of Decision

- **Status**: Proposed | Accepted | Deprecated | Superseded
- **Date**: YYYY-MM-DD
- **Authors**: Team

## Context

Describe the context, problem statement, and forces at play.

## Decision

Describe the decision taken and the architectural rationale.

## Consequences

- **Positive**: Benefits and capabilities gained.
- **Negative**: Trade-offs, migration burden, or constraints imposed.
`
}
