package adopt

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
	"time"
)

// Excerpts of the pre-commit hooks the runners install, holding the lines the audit recognises:
// Lefthook 2.1.14's fingerprint and dispatch line (internal/templates/hook.tmpl), and the ID line
// and templated arguments pre-commit 4.6.2 writes (resources/hook-tmpl). The live replay below
// checks the same markers against the hooks the installed runners write.
const (
	lefthookHookExcerpt  = "#!/bin/sh\n\nif [ \"$LEFTHOOK\" = \"0\" ]; then\n  exit 0\nfi\n\ncall_lefthook run \"pre-commit\" \"$@\"\n"
	preCommitHookExcerpt = "#!/usr/bin/env bash\n# File generated by pre-commit: https://pre-commit.com\n" +
		"# ID: 138fd403232d2ddd5efb44317e38bf03\n\n# start templated\nINSTALL_PYTHON=/usr/bin/python3\n" +
		"ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit)\n# end templated\n"
	placeholderHook = "#!/bin/sh\nexit 0\n"
)

// Pre-commit framework configurations: one whose local hooks run both praetor commands, and one
// whose hooks omit the audit.
const (
	preCommitContextHook = "repos:\n  - repo: local\n    hooks:\n" +
		"      - id: praetor-context\n        name: context\n        entry: praetorctl compile-context --verify\n" +
		"        language: system\n        pass_filenames: false\n"
	preCommitBothCommands = preCommitContextHook +
		"      - id: praetor-audit\n        name: audit\n        entry: praetorctl\n        args: [audit, --offline]\n" +
		"        language: system\n        pass_filenames: false\n"
)

// hookRunnerRepo returns a hermetic Git checkout with lefthook.yml and/or .pre-commit-config.yaml
// as asked, and its hooks directory .git/hooks. Git reads no global or system configuration, so
// a developer's core.hooksPath cannot move the directory the audit consults.
func hookRunnerRepo(t *testing.T, lefthook bool, preCommit string) (string, string) {
	t.Helper()
	requireGit(t)
	t.Setenv("GIT_CONFIG_GLOBAL", os.DevNull)
	t.Setenv("GIT_CONFIG_NOSYSTEM", "1")
	root := filepath.Join(t.TempDir(), "repo")
	initTestGit(t, root)
	if lefthook {
		mustWrite(t, filepath.Join(root, lefthookFile), "pre-commit:\n  commands: {}\n")
	}
	if preCommit != "" {
		mustWrite(t, filepath.Join(root, preCommitConfigFile), preCommit)
	}
	return root, filepath.Join(root, ".git", "hooks")
}

// installTestHook writes content as the pre-commit hook in hooksDir with mode.
func installTestHook(t *testing.T, hooksDir, content string, mode os.FileMode) string {
	t.Helper()
	path := filepath.Join(hooksDir, preCommitHook)
	mustWrite(t, path, content)
	if err := os.Chmod(path, mode); err != nil {
		t.Fatal(err)
	}
	return path
}

// TestAuditInstalledGitHook_Positive_KnownRunners (#175): the hook of each known runner passes
// beside the configuration that runner reads, and the line names the runner and the file.
func TestAuditInstalledGitHook_Positive_KnownRunners(t *testing.T) {
	for _, tc := range []struct {
		name, hook, preCommit, want string
		lefthook                    bool
	}{
		{"lefthook", lefthookHookExcerpt, "", "via lefthook, lefthook.yml) verified active.", true},
		{"fallback", buildFallbackPreCommitScript(), "", "via the praetor fallback hook, lefthook.yml) verified active.", true},
		{"pre-commit framework", preCommitHookExcerpt, preCommitBothCommands, "via the pre-commit framework, .pre-commit-config.yaml) verified active.", false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			root, hooks := hookRunnerRepo(t, tc.lefthook, tc.preCommit)
			path := installTestHook(t, hooks, tc.hook, 0o700)
			line, err := AuditInstalledGitHook(t.Context(), root)
			if err != nil || !strings.HasPrefix(line, "[PASS] Local Git hooks ("+path) || !strings.HasSuffix(line, tc.want) {
				t.Fatalf("line %q, err %v; want suffix %q", line, err, tc.want)
			}
		})
	}
}

// TestAuditInstalledGitHook_Negative_UnprovenHooks (#175): a placeholder, a framework hook whose
// configuration omits the audit, a framework configuration with no hook installed, a lefthook
// hook without lefthook.yml and a framework hook that reads another file all fail, naming the
// path and what was found.
func TestAuditInstalledGitHook_Negative_UnprovenHooks(t *testing.T) {
	for _, tc := range []struct {
		name, hook, preCommit string
		lefthook              bool
		want                  []string
	}{
		{"placeholder", placeholderHook, "", true, []string{"was not written by a known hook runner", `found a 17-byte file whose first line is "#!/bin/sh"`}},
		{"framework config omits audit", preCommitHookExcerpt, preCommitContextHook, true, []string{"written by the pre-commit framework, but", "does not run 'praetorctl audit'"}},
		{"framework config without hook", "", preCommitBothCommands, false, []string{"is missing or inactive", "'pre-commit install'"}},
		{"lefthook hook without lefthook.yml", lefthookHookExcerpt, preCommitBothCommands, false, []string{"written by lefthook, but lefthook.yml is missing"}},
		{"framework hook reads another file", strings.Replace(preCommitHookExcerpt, "--config=.pre-commit-config.yaml", "--config=ci/hooks.yaml", 1),
			preCommitBothCommands, false, []string{`the hook reads "ci/hooks.yaml", not .pre-commit-config.yaml`}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			root, hooks := hookRunnerRepo(t, tc.lefthook, tc.preCommit)
			path := filepath.Join(hooks, preCommitHook)
			if tc.hook != "" {
				installTestHook(t, hooks, tc.hook, 0o700)
			}
			_, err := AuditInstalledGitHook(t.Context(), root)
			if err == nil || !strings.HasPrefix(err.Error(), "[FAIL] Pre-commit hook "+path) {
				t.Fatalf("err %v; want a failure naming %s", err, path)
			}
			for _, want := range tc.want {
				if !strings.Contains(err.Error(), want) {
					t.Fatalf("err %v; want %q", err, want)
				}
			}
		})
	}
}

// TestAuditInstalledGitHook_Negative_NotExecutableOnUnix: a known runner's hook without the
// owner execute bit is skipped by git on Unix, so the audit fails it there. Windows has no
// execute bit; TestHookRunnable_Boundary_PlatformRules covers its rule on every host.
func TestAuditInstalledGitHook_Negative_NotExecutableOnUnix(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("Windows has no execute bit; git there runs a hook that starts with #! (TestHookRunnable_Boundary_PlatformRules)")
	}
	root, hooks := hookRunnerRepo(t, true, "")
	installTestHook(t, hooks, lefthookHookExcerpt, 0o600)
	_, err := AuditInstalledGitHook(t.Context(), root)
	if err == nil || !strings.Contains(err.Error(), "written by lefthook, is not executable (mode -rw-------)") {
		t.Fatalf("non-executable hook: %v", err)
	}
}

// fakeHookInfo is an os.FileInfo carrying only a mode, so both platform rules run on every host.
type fakeHookInfo struct{ mode os.FileMode }

func (f fakeHookInfo) Name() string       { return preCommitHook }
func (f fakeHookInfo) Size() int64        { return 0 }
func (f fakeHookInfo) Mode() os.FileMode  { return f.mode }
func (f fakeHookInfo) ModTime() time.Time { return time.Time{} }
func (f fakeHookInfo) IsDir() bool        { return false }
func (f fakeHookInfo) Sys() any           { return nil }

// TestHookRunnable_Boundary_PlatformRules: git's is_executable test. On Unix the owner execute
// bit decides, group and other bits alone do not; on Windows, which has no execute bit, a file
// starting with #! runs whatever its mode, and one without it does not.
func TestHookRunnable_Boundary_PlatformRules(t *testing.T) {
	script := []byte(lefthookHookExcerpt)
	for _, tc := range []struct {
		name, goos string
		mode       os.FileMode
		data       []byte
		ok         bool
	}{
		{"unix owner execute", "linux", 0o700, script, true},
		{"unix group and other execute only", "darwin", 0o655, script, false},
		{"windows shebang without execute bit", "windows", 0o644, script, true},
		{"windows without shebang", "windows", 0o755, []byte("call_lefthook run \"pre-commit\"\n"), false},
	} {
		err := hookRunnable(fakeHookInfo{mode: tc.mode}, tc.data, tc.goos)
		if (err == nil) != tc.ok {
			t.Errorf("%s: err %v, want ok=%v", tc.name, err, tc.ok)
		}
	}
}

// TestAuditGitHookRunners_Boundary_BothConfigurations: with lefthook.yml and
// .pre-commit-config.yaml both present, the installed hook decides which configuration is the
// runner's. Lefthook's hook passes although the framework configuration omits the audit; the
// framework's hook fails on it, lefthook.yml notwithstanding. The configuration gate, which reads
// no hook, is satisfied by lefthook.yml.
func TestAuditGitHookRunners_Boundary_BothConfigurations(t *testing.T) {
	root, hooks := hookRunnerRepo(t, true, preCommitContextHook)
	hooksConfig, err := AuditGitHookConfig(t.Context(), nil, root)
	if err != nil || hooksConfig.File != lefthookFile || hooksConfig.Runner != "lefthook" {
		t.Fatalf("configuration gate with both files: %+v, %v", hooksConfig, err)
	}
	installTestHook(t, hooks, lefthookHookExcerpt, 0o700)
	if line, err := AuditInstalledGitHook(t.Context(), root); err != nil || !strings.Contains(line, "via lefthook, lefthook.yml") {
		t.Fatalf("lefthook hook beside both files: %q, %v", line, err)
	}
	installTestHook(t, hooks, preCommitHookExcerpt, 0o700)
	if _, err := AuditInstalledGitHook(t.Context(), root); err == nil || !strings.Contains(err.Error(), "does not run 'praetorctl audit'") {
		t.Fatalf("framework hook beside both files: %v", err)
	}
}

// TestAuditInstalledGitHook_Boundary_CoreHooksPath: a hook in the directory a core.hooksPath
// inside the working tree names no longer passes (#61), even with lefthook's hook installed
// there and in .git/hooks; hooks_path_audit_test.go covers the rule.
func TestAuditInstalledGitHook_Boundary_CoreHooksPath(t *testing.T) {
	root, defaultHooks := hookRunnerRepo(t, true, "")
	mustWrite(t, filepath.Join(root, ".git", "config"), "[core]\n\thooksPath = .githooks\n")
	installTestHook(t, defaultHooks, lefthookHookExcerpt, 0o700)
	installTestHook(t, filepath.Join(root, ".githooks"), lefthookHookExcerpt, 0o700)
	if line, err := AuditInstalledGitHook(t.Context(), root); err == nil || !strings.Contains(err.Error(), `core.hooksPath is set to ".githooks" (local scope`) {
		t.Fatalf("hook in a core.hooksPath inside the working tree: %q, %v", line, err)
	}
}
