package adopt_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/cordanaLLM/praetor/internal/adopt"
	"github.com/cordanaLLM/praetor/internal/forge"
)

func TestNeutralText_Positive(t *testing.T) {
	harness := adopt.BuildAgentHarnessDirectives()
	if strings.Contains(harness, "[bot]") {
		t.Errorf("Harness directives contain bot login: %q", harness)
	}
	if !strings.Contains(harness, "CI re-checks every pull request in an isolated runner") {
		t.Errorf("Harness directives missing the neutral CI sentence")
	}

	labels := string(forge.DefaultLabelTaxonomy())
	if strings.Contains(labels, "[bot]") {
		t.Errorf("Labels YAML contains bot login: %q", labels)
	}
	if !strings.Contains(labels, "Automated configuration sync generated by Praetor") {
		t.Errorf("Labels YAML missing the neutral sync description")
	}
	if strings.Count(labels, "- name:") != 8 {
		t.Errorf("Labels YAML should contain exactly 8 labels")
	}
}

func TestNeutralText_Negative(t *testing.T) {
	// A negative test ensures that an explicitly non-neutral string fails the check.
	// Since BuildAgentHarnessDirectives has no parameters, we just assert its output doesn't match the old text.
	harness := adopt.BuildAgentHarnessDirectives()
	if strings.Contains(harness, "re-checks every pull request in ephemeral isolated sandbox") {
		t.Errorf("Harness directives contain old non-neutral text")
	}
}

func TestNeutralText_Boundary(t *testing.T) {
	// Check that the adopt workflow actually defaults to github-actions[bot].
	// This satisfies the requirement to test the default identity.
	repoRoot := filepath.Join("..", "..")
	adoptYml, err := os.ReadFile(filepath.Join(repoRoot, ".github", "workflows", "adopt.yml"))
	if err != nil {
		t.Fatalf("Failed to read adopt.yml: %v", err)
	}

	content := string(adoptYml)
	if !strings.Contains(content, "${{ vars.PRAETOR_BOT_NAME || 'github-actions[bot]' }}") {
		t.Errorf("adopt.yml missing fallback for PRAETOR_BOT_NAME")
	}
	if !strings.Contains(content, "${{ vars.PRAETOR_BOT_EMAIL || '41898282+github-actions[bot]@users.noreply.github.com' }}") {
		t.Errorf("adopt.yml missing fallback for PRAETOR_BOT_EMAIL")
	}
}
