package adopt

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/cordanaLLM/praetor/internal/agentcontext"
	"github.com/cordanaLLM/praetor/internal/flavor"
	"github.com/cordanaLLM/praetor/internal/forge"
	"github.com/cordanaLLM/praetor/internal/ghworkflow"
	"github.com/cordanaLLM/praetor/internal/hisscatalog"
)

// neutralWorkflows is the CI a full adoption of a documented Go library scaffolds: the
// documentation gate and the go-library flavor's ci.yml, read from their bodies.
func neutralWorkflows(t *testing.T) []scaffoldedWorkflow {
	t.Helper()
	workflows, err := workflowRuns([]flavor.PlannedTemplate{
		{Path: DocumentationWorkflowFile, Content: DocumentationWorkflow()},
		{Path: ".github/workflows/ci.yml", Content: renderedTemplate(t, "go/ci-go.yml.tmpl")},
	})
	if err != nil {
		t.Fatal(err)
	}
	return workflows
}

// neutralDirectives renders the harness directives of a full adoption with the given hook
// activation and scaffolded CI.
func neutralDirectives(hooks hookActivation, workflows []scaffoldedWorkflow) string {
	return buildAgentHarnessDirectives(harnessFacts{pipelines: hisscatalog.AllPipelines, hooks: hooks,
		targets: agentcontext.AllVendorTargets(), workflows: workflows})
}

func TestNeutralText_Positive(t *testing.T) {
	harness := neutralDirectives(hooksLefthook, neutralWorkflows(t))
	if strings.Contains(harness, "[bot]") {
		t.Errorf("Harness directives contain bot login: %q", harness)
	}
	// Adoption runs no praetorctl gate on the server, and rule 5 names the CI it does scaffold
	// with what that CI runs, read from the workflow bodies (BUG-804).
	for _, want := range []string{
		"Adoption adds no server-side `praetorctl` gate run. Scaffolded CI: ",
		"`" + DocumentationWorkflowFile + "` runs step `" + ghworkflow.HostedGateDraftStepName + "`, `node tools/markdownlint/verify.mjs`",
		"`.github/workflows/ci.yml` runs `go vet ./...`, `go test -race ./...`",
	} {
		if !strings.Contains(harness, want) {
			t.Errorf("rule 5 lacks %q:\n%s", want, harness)
		}
	}

	labels := string(forge.DefaultLabelTaxonomy())
	if strings.Contains(labels, "[bot]") {
		t.Errorf("Labels YAML contains bot login: %q", labels)
	}
	if !strings.Contains(labels, "Automated configuration sync generated by Praetor") {
		t.Errorf("Labels YAML missing the neutral sync description")
	}
	if strings.Count(labels, "- name:") != 14 {
		t.Errorf("Labels YAML should contain exactly 14 labels")
	}
}

func TestNeutralText_Negative(t *testing.T) {
	// Neither the old bot sandbox claim, nor a pull request re-check, nor a denial of the CI
	// adoption does scaffold appears, whatever the hooks.
	for _, hooks := range []hookActivation{hooksNone, hooksInactive, hooksLefthook} {
		harness := neutralDirectives(hooks, neutralWorkflows(t))
		for _, claim := range []string{"re-checks every pull request", "[bot]", "no server-side re-check"} {
			if strings.Contains(harness, claim) {
				t.Errorf("hooks %d: harness directives claim %q:\n%s", hooks, claim, harness)
			}
		}
	}
	// Without a scaffolded workflow, rule 5 says the gates run only locally and names no CI.
	bare := neutralDirectives(hooksLefthook, nil)
	if !strings.Contains(bare, "Adoption scaffolds no CI workflow: `praetorctl` gates run local only.") || strings.Contains(bare, "Scaffolded CI:") {
		t.Errorf("rule 5 without scaffolded CI:\n%s", bare)
	}
}

func TestNeutralText_Boundary(t *testing.T) {
	// Check that the adopt workflow actually defaults to github-actions[bot].
	// This satisfies the requirement to test the default identity.
	repoRoot := filepath.Join("..", "..")
	adoptYml, err := os.ReadFile(filepath.Join(repoRoot, ".github", "workflows", "adopt.yml"))
	if err != nil {
		t.Fatalf("Failed to read adopt.yml: %v", err)
	}

	content := string(adoptYml)
	if !strings.Contains(content, "${{ vars.PRAETOR_BOT_NAME || 'github-actions[bot]' }}") {
		t.Errorf("adopt.yml missing fallback for PRAETOR_BOT_NAME")
	}
	if !strings.Contains(content, "${{ vars.PRAETOR_BOT_EMAIL || '41898282+github-actions[bot]@users.noreply.github.com' }}") {
		t.Errorf("adopt.yml missing fallback for PRAETOR_BOT_EMAIL")
	}
}
