package adopt

import (
	"context"
	"fmt"
	"path/filepath"

	"github.com/cordanaLLM/praetor/internal/compiler"
	"github.com/cordanaLLM/praetor/internal/config"
	"github.com/cordanaLLM/praetor/internal/forge"
	"github.com/cordanaLLM/praetor/internal/paperclip"
)

const (
	rulesetFile      = ".github/rulesets/main.json"
	labelsFile       = ".config/labels.yaml"
	paperclipFile    = ".paperclip/harness.json"
	auditorAgentFile = ".agents/agents/repo-auditor.md"
	gatekeeperFile   = ".agents/agents/repo-gatekeeper.md"
)

// buildRulesetJSON delegates policy rendering to the same service as CLI sync and
// remote forge reconciliation. Context selection remains repository-specific.
func buildRulesetJSON(policy config.BranchProtectionPolicy, contexts []string) (string, error) {
	data, err := forge.RenderRepositoryRuleset(policy, contexts)
	return string(data), err
}

func adoptionBranchPolicy(ctx context.Context, s *adoptSession) (config.BranchProtectionPolicy, error) {
	if s.policy != nil {
		return s.policy.Policy.BranchProtection, nil
	}
	// A dry-run without pinned catalog inputs still has a selected manifest. Only
	// branch defaults and its explicit overrides are claimed by this fallback.
	manifest, err := manifestForLock(ctx, s)
	if err != nil {
		return config.BranchProtectionPolicy{}, err
	}
	policy := config.DefaultPolicy()
	policy.ApplyOverrides(manifest.Overrides)
	return policy.BranchProtection, nil
}

func requiredStatusContexts(repoPath string) ([]string, error) {
	return forge.RequiredStatusContexts(context.Background(), repoPath)
}

func reconcileBranchRuleset(ctx context.Context, s *adoptSession) error {
	contexts, err := forge.RequiredStatusContexts(ctx, s.repoPath)
	if err != nil {
		return err
	}
	policy, err := adoptionBranchPolicy(ctx, s)
	if err != nil {
		return err
	}
	content, err := buildRulesetJSON(policy, contexts)
	if err != nil {
		return err
	}
	_, err = s.scaffoldFile(scaffold{
		rel:      rulesetFile,
		perm:     filePerm,
		content:  []byte(content),
		force:    true,
		created:  fmt.Sprintf("Scaffolded declarative branch protection ruleset (%d required status checks derived from workflows)", len(contexts)),
		verified: "Existing branch protection ruleset verified present",
	})
	return err
}

func reconcileLabels(_ context.Context, s *adoptSession) error {
	_, err := s.scaffoldFile(scaffold{
		rel:      labelsFile,
		perm:     filePerm,
		content:  []byte(buildDefaultLabelsYAML()),
		force:    true,
		created:  "Scaffolded repository label taxonomy",
		verified: "Existing repository label taxonomy verified present",
	})
	return err
}

func buildDefaultLabelsYAML() string {
	return `version: 1
labels:
  - name: "hiss-violation"
    color: "d73a4a"
    description: "Code introduces a regression against HISS invariants"
  - name: "hiss-waiver"
    color: "fbca04"
    description: "Requires cryptographically signed waiver approval"
  - name: "standards-sync"
    color: "0075ca"
    description: "Automated configuration sync generated by cordana-standards[bot]"
`
}

func reconcilePaperclip(ctx context.Context, s *adoptSession) error {
	full, err := repoFile(s.repoPath, paperclipFile)
	if err != nil {
		return err
	}
	if fileExists(full) && !s.opts.Force {
		s.report.recordReconciled(paperclipFile, "Existing Paperclip agent runtime harness verified present")
		return nil
	}
	if !s.opts.DryRun {
		harness, err := paperclip.SynthesizeHarness(ctx, s.repoPath)
		if err != nil {
			return fmt.Errorf("synthesize paperclip harness: %w", err)
		}
		if err := paperclip.WriteHarness(harness, s.repoPath); err != nil {
			return fmt.Errorf("write paperclip harness: %w", err)
		}
	}
	s.report.recordCreated(paperclipFile, "Scaffolded Paperclip agent runtime harness and AGit rules")
	return nil
}

// generatedPersonas are the canonical personas adoption writes into an adopted repository.
// The context gate lints every canonical persona (#369), so text praetor generates here has
// to pass praetor's own lint. Both were prose until #380 and #381 reported the gate failing
// on personas nobody had edited. Keeping the set in one place is what lets
// TestGeneratedPersonasPassCavemanLint catch the next one before an adopter's push does.
func generatedPersonas() []scaffold {
	return []scaffold{{
		rel:      auditorAgentFile,
		perm:     filePerm,
		content:  []byte(defaultAuditorAgentMD),
		force:    true,
		created:  "Scaffolded repository auditor agent definition",
		verified: "Existing repository auditor agent definition verified present",
	}, {
		rel:      gatekeeperFile,
		perm:     filePerm,
		content:  []byte(defaultGatekeeperAgentMD),
		force:    true,
		created:  "Scaffolded repository gatekeeper agent definition",
		verified: "Existing repository gatekeeper agent definition verified present",
	}}
}

func reconcileAgentDefinitions(ctx context.Context, s *adoptSession) error {
	personas := generatedPersonas()
	for i := 0; i < len(personas) && i < maxTranspileTargets; i++ {
		if _, err := s.scaffoldFile(personas[i]); err != nil {
			return err
		}
	}
	if s.opts.DryRun {
		return nil
	}
	projected, err := compiler.CompileAgents(ctx, filepath.Join(s.repoPath, ".agents", "agents"), s.repoPath)
	if err != nil {
		return fmt.Errorf("compile agent definitions: %w", err)
	}
	for i := 0; i < len(projected) && i < maxTranspileTargets; i++ {
		s.report.recordCreated(projected[i].VendorTarget, "Projected canonical agent definition to vendor target")
	}
	return nil
}

const defaultAuditorAgentMD = `---
name: repo-auditor
description: "Autonomous agent for repository HISS invariant sweeps and praetorctl compliance."
mainAgent: true
subagent: true
commandExecutionPolicy: auto
---

# Repository Governance Auditor Persona

Authoritative repository governance auditor. Purpose: run autonomous sweeps across codebases and git commits; guarantee 100% adherence to declared standards.

## Execution Command
` + "```bash\npraetorctl audit\n```\n"

const defaultGatekeeperAgentMD = `---
name: repo-gatekeeper
description: "Autonomous subagent for dependency verification, SCA security scans, and worktree gating."
mainAgent: true
subagent: true
commandExecutionPolicy: auto
---

# Repository Gatekeeper Persona

Repository gatekeeper. Mission: enforce anti-direct-merge policy strictly; verify every verification gate before shipping.

## Execution Command
` + "```bash\npraetorctl gate run --target=. --dry-run\n```\n"
