// SPDX-FileCopyrightText: 2026 lusoris <lusoris@pm.me>
//
// SPDX-License-Identifier: EUPL-1.2

package adopt

import (
	"path/filepath"
	"strings"
	"testing"
)

// A repository without a runnable verification plan gets the placeholder Makefile, whose build
// and test recipes print a pointer to the report and exit 1. That placeholder is adoption's own
// output: once the repository gains a runnable plan, a plain run replaces it with the runnable
// verify-all, as it replaces every other earlier Praetor rendering (#638). An edited placeholder
// is the adopter's and stays untouched.

const cargoManifestFixture = "[package]\nname = 'fixture'\nversion = '0.1.0'\n"

// placeholderPlan is a plan with no runnable command, the plan the placeholder is rendered from.
func placeholderPlan() *VerificationPlan {
	return &VerificationPlan{Status: verificationUnavailable, Build: [][]string{}, Test: [][]string{}}
}

// verificationGatePillar returns the Verification Gate pillar of report.
func verificationGatePillar(t *testing.T, report *AdoptReport) Pillar {
	t.Helper()
	for _, pillar := range report.Pillars() {
		if pillar.Name == "Verification Gate" {
			return pillar
		}
	}
	t.Fatal("report has no Verification Gate pillar")
	return Pillar{}
}

// adoptPlain runs a plain adoption (no --force) of root and fails on an error.
func adoptPlain(t *testing.T, root string, dryRun bool) *AdoptReport {
	t.Helper()
	report, err := Adopt(t.Context(), AdoptOptions{
		Path: root, Profile: "framework", LockSourceRoot: newAdoptLockSource(t), DryRun: dryRun,
	})
	if err != nil {
		t.Fatal(err)
	}
	return report
}

// Positive: the placeholder a first adoption wrote is regenerated by a plain run once the
// repository declares a build and a test command, the preview agrees with the run, and the
// Verification Gate reports ready.
func TestVerificationPlaceholderRegeneratedOncePlanIsRunnable(t *testing.T) {
	root := newTestRepo(t, "placeholder")
	first := adoptPlain(t, root, false)
	placeholder := mustRead(t, filepath.Join(root, makefileName))
	if first.Verification.Status != verificationUnavailable || !strings.Contains(placeholder, unavailableRecipeLine) {
		t.Fatalf("first adoption wrote no placeholder: %+v %q", first.Verification, placeholder)
	}
	mustWrite(t, filepath.Join(root, "Cargo.toml"), cargoManifestFixture)
	before := snapshotTree(t, root)
	preview := adoptPlain(t, root, true)
	assertTreeUnchanged(t, before, snapshotTree(t, root))
	applied := adoptPlain(t, root, false)
	if preview.Verification.Status != verificationDeclared || applied.Verification.Status != verificationDeclared {
		t.Fatalf("placeholder kept the plan from being declared: preview %+v, applied %+v", preview.Verification, applied.Verification)
	}
	want, err := mergeDocumentationMakefile(buildMakefile(applied.Verification), false)
	if err != nil {
		t.Fatal(err)
	}
	if got := mustRead(t, filepath.Join(root, makefileName)); got != want {
		t.Fatalf("placeholder not regenerated:\n%s\nwant\n%s", got, want)
	}
	if pillar := verificationGatePillar(t, applied); pillar.Status != PillarReady {
		t.Fatalf("Verification Gate = %s %v, want ready", pillar.Status, pillar.Warnings)
	}
	after := snapshotTree(t, root)
	adoptPlain(t, root, false)
	assertTreeUnchanged(t, after, snapshotTree(t, root))
}

// unavailableRecipeLine is the line of the placeholder recipe that names the report.
const unavailableRecipeLine = "'Project verification unavailable; see the adoption report and AGENTS.md.'"

// Positive: every placeholder rendering adoption wrote -- the current one and the one from before
// the configured-sources gate joined verify-all -- is its own output for a runnable plan, with or
// without the documentation block.
func TestVerificationPlaceholderRenderingsAreReplaceable(t *testing.T) {
	root := newTestRepo(t, "placeholder-renderings")
	mustWrite(t, filepath.Join(root, "Cargo.toml"), cargoManifestFixture)
	plan, err := resolveVerificationPlan(t.Context(), root)
	if err != nil {
		t.Fatal(err)
	}
	for name, rendering := range map[string]string{
		"current":            buildMakefile(placeholderPlan()),
		"before-source-gate": priorSourceGateMakefile(placeholderPlan()),
	} {
		withBlock, mergeErr := mergeDocumentationMakefile(rendering, false)
		if mergeErr != nil {
			t.Fatal(mergeErr)
		}
		for form, data := range map[string]string{"bare": rendering, "documentation-block": withBlock} {
			if !isReplaceableVerificationMakefile(data, plan) {
				t.Errorf("%s placeholder (%s) is not recognised as adoption's output", name, form)
			}
		}
	}
}

// Negative: a placeholder the adopter edited is the adopter's Makefile. A plain run keeps it
// byte for byte, apart from the documentation block, and does not declare the plan runnable.
func TestVerificationEditedPlaceholderIsPreserved(t *testing.T) {
	root := newTestRepo(t, "placeholder-edited")
	mustWrite(t, filepath.Join(root, "Cargo.toml"), cargoManifestFixture)
	existing := "# operator changes\n" + buildMakefile(placeholderPlan())
	mustWrite(t, filepath.Join(root, makefileName), existing)
	report := adoptPlain(t, root, false)
	want, err := mergeDocumentationMakefile(existing, false)
	if err != nil {
		t.Fatal(err)
	}
	if got := mustRead(t, filepath.Join(root, makefileName)); got != want {
		t.Fatalf("edited placeholder changed:\n%s\nwant\n%s", got, want)
	}
	if report.Verification.Status == verificationDeclared {
		t.Fatalf("edited placeholder certified as a declared plan: %+v", report.Verification)
	}
}

// Boundary: while the plan is still unavailable the placeholder is the current rendering, not an
// earlier one, so it is not replaceable and a re-run leaves the tree untouched.
func TestVerificationPlaceholderIsCurrentWhilePlanUnavailable(t *testing.T) {
	root := newTestRepo(t, "placeholder-current")
	adoptPlain(t, root, false)
	plan, err := resolveVerificationPlan(t.Context(), root)
	if err != nil {
		t.Fatal(err)
	}
	if plan.Status != verificationUnavailable {
		t.Fatalf("fixture plan = %+v, want unavailable", plan)
	}
	if isReplaceableVerificationMakefile(mustRead(t, filepath.Join(root, makefileName)), plan) {
		t.Fatal("the current placeholder is reported as an earlier rendering")
	}
	after := snapshotTree(t, root)
	adoptPlain(t, root, false)
	assertTreeUnchanged(t, after, snapshotTree(t, root))
}
