apiVersion: v1
kind: Service
metadata:
  name: {{ include "praetor.fullname" . }}
  labels:
    {{- include "praetor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http-probes
  selector:
    {{- include "praetor.selectorLabels" . | nindent 4 }}
